### ISSUE TITLE
[Conan] Upgrade PcapPlusPlus receipt to support libpcap 1.10.1

### ISSUE THREAD

**Issue by leoparente** [seladb/PcapPlusPlus#1077]
Hello @seladb 

We use PcapPlusPlus in our [Pktvisor](https://github.com/orb-community/pktvisor) Project through Conan package Manager . After the release of PcapPlusPlus for Windows on Conan by using `npcap` we added that support on our project as well.

By adding support to Windows on our Pktvisor Project we started to see increase on OS packets drops on Linux machines.
Then I realized that before the Windows support, we explicit setup libpcap `v1.10.0` on our conanfile. After that change, we started relying on PcapPlusPlus receipt that is currently using libpcap `v1.9.1`: 
https://github.com/conan-io/conan-center-index/blob/master/recipes/pcapplusplus/all/conanfile.py#L47

Could you update the `libpcap` dependency to match the latest released there on conan center? it currently would be `v1.10.1`.
because specifying it on our side breaks Windows build because libpcap is only supported on Linux, then It would require a workaround on our side.

**Comment by seladb** [comment]
Thank you for letting us know @leoparente !

I opened this PR in `conan-center-index`: https://github.com/conan-io/conan-center-index/pull/16190

Please note it usually takes the Conan folks some time to respond to PRs, probably because they have a lot on their plates.
Maybe you can comment on the PR and try to promote it...

**Comment by leoparente** [comment]
Thanks for the quick response @seladb. I will to that there.

**Comment by seladb** [comment]
@leoparente the libpcap upgrade was done as part of [this PR](https://github.com/conan-io/conan-center-index/pull/16605#) that upgrades the PcapPlusPlus recipe to Conan 2.0. Since the PR was merged we can close this issue.

Thank you again @jcar87 for working on the recipe upgrade, much appreciated! 🙏 ❤️
