### ISSUE TITLE
Incorrect Parsing of Encrypted Handshake Message

### ISSUE THREAD

**Issue by axmahr** [seladb/PcapPlusPlus#1085]
Hello!

in some cases, Encrypted Handshake Messages are parsed incorrectly, when the first encrypted bytes of the message match an existing handshake type. In the attached pcap file in [bug2.zip](https://github.com/seladb/PcapPlusPlus/files/10862561/bug2.zip) you can see that the encrypted handshake message begins with leading zeroes. Running the following code snippet shows us that these zeroes are interpreted as two Hello Request messages (handshake type 0).
```c++
#include <PcapFileDevice.h>
#include <Packet.h>
#include <SSLLayer.h>
#include <SSLHandshake.h>
#include <iostream>

int main() {

    pcpp::PcapFileReaderDevice pcapReader("bug2.pcap");
    pcapReader.open();

    pcpp::RawPacket rawPacket;
    while(pcapReader.getNextPacket(rawPacket)){
        pcpp::Packet parsedPacket(&rawPacket);

        // get the 2nd ssl layer of the packet (encrypted handshake message)
        pcpp::SSLLayer *sslLayer = dynamic_cast<pcpp::SSLLayer*>(parsedPacket.getLayerOfType(pcpp::SSL, 1));
        pcpp::SSLHandshakeLayer *handshakeLayer = dynamic_cast<pcpp::SSLHandshakeLayer *>(sslLayer);
        uint64_t numHandshakeMessages = handshakeLayer->getHandshakeMessagesCount();

        std::cout << "We have " << numHandshakeMessages << " handshake messages:" << std::endl;
        for (uint64_t i = 0; i < numHandshakeMessages; ++i) {
            pcpp::SSLHandshakeMessage *handshakeMessage = dynamic_cast<pcpp::SSLHandshakeLayer *>(sslLayer)->getHandshakeMessageAt(i);
            std::cout << i <<". " << handshakeMessage->toString();
            std::cout << ", MessageLength: " << handshakeMessage->getMessageLength() << std::endl;
        }
    }
}
```
The incorrect interpretation of these zeroes in `SSLHandshakeMessage::createHandshakeMessage` and the following updates of indices w.r.t. `getMessageLength()` in the constructor of `SSLHandshakeLayer` lead to more falsely recognized messages.
All in all, the code snippet produces the following output:
```
We have 3 handshake messages:
0. Hello Request message, MessageLength: 4
1. Hello Request message, MessageLength: 4
2. Certificate message, MessageLength: 32
```
The application data record gets parsed correctly.

I couldn't figure out a a quick way to solve this issue, it might be difficult.

**Comment by seladb** [comment]
Thanks for catching this @axmahr !

I'm not sure there is an easy/full-proof way to solve it, but I took a look at Wireshark source code and they have a pretty interesting heuristics to detect encrypted handshake messages:
https://github.com/wireshark/wireshark/blob/4c9467340108691ac7053cc16ecb3e793894444a/epan/dissectors/packet-tls.c#L2359

1. Handshake layers of less than 16 bytes are most likely not encrypted
2. If the first 5 bytes of the handshake layer data are zeros (which is the case in your example) - it's most likely an encrypted layer - because it doesn't make sense to have two successive HelloRequest messages (type=0x00 length=0x000000, type=0x00)
3. If the handshake layer comes after ChangeCipherSpec (which is also the case in your example) - it has to be encrypted
4. If the message type of the first message doesn't make sense, it may be encrypted (or the packet is corrupted)
5. If the length of the first message is too large (more than 64k), it's probably encrypted

I think we can implement most of these heuristics in PcapPlusPlus TLS/SSL parsing. Would you like to give it a shot?

**Comment by axmahr** [comment]
Hi @seladb 
Thanks a lot for your fast response and for sharing how Wireshark approaches this.
I created a PR #1087 where I basically combined your points 1., 2., 4. and 5. I didn't find a way to implement the 3. point on the fly.

**Comment by seladb** [comment]
@axmahr thank you so much for reporting this bug and providing a fix, much appreciated! 🙏 ❤️
