### ISSUE TITLE
How to know FTP-DATA packet from where?

### ISSUE THREAD

**Issue by luckygg** [seladb/PcapPlusPlus#1110]
Hi all.

When the notepad file was transferred using the FTP protocol, I can see the packets were divided using the FTP-DATA protocol on Wireshark.

And in Wireshark, I can see the STOR command and original file name in the FTP-DATA packet.

Is there a way using pcaplusplus to find out which file transfer the FTP-DATA packets were split from?

Thank you.

**Comment by egecetin** [comment]
Hi @luckygg,

The registered IANA port for FTP-DATA is 20 (https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers) but for most real cases the data port negotiated during the control communication and port is unpredictable. If I'm not mistaken Wireshark uses static port approach, this means if its port 20 it should be FTP-DATA assumption, to determine the FTP-DATA protocol (Check [here](https://gitlab.com/wireshark/wireshark/-/blob/master/epan/dissectors/packet-ftp.c#L93) and [here](https://gitlab.com/wireshark/wireshark/-/blob/master/epan/dissectors/packet-ftp.c#L1872)) 

Currently, at PcapPlusPlus, only the FTP control messages are supported, and it could be a nice addition to the library (static port approach is enough I think).

**Comment by seladb** [comment]
@egecetin do you think we should keep this issue as a potential enhancement?

**Comment by egecetin** [comment]
At first glance, I thought the FTP-DATA also includes some commands and Wireshark parses info from data conversation, but I double checked [here](https://github.com/wireshark/wireshark/blob/474a87df9c9251e587ae059393ad134d7ce8b683/epan/dissectors/packet-ftp.c#L1539) and looks like Wireshark just links back information from control conversation. So, from my understanding FTP-DATA basically equals to `PayloadLayer` (just binary or ASCII data).

There is no need for any additional parser since the payload layer can be used. Maybe we can just define a FtpDataLayer with only port checking and a layer inherited from payload layer to prevent confusion or close the issue. What do you think?

**Comment by seladb** [comment]
@egecetin thanks for checking! We can create `FtpDataLayer` which looks a lot like `PayloadLayer` but identifies itself as FTP.

The only problem is that the port is dynamic. As of now PcapPlusPlus cannot infer ports (or any other data) from one packet to another, which means that when we see FTP control data, parse it and identify the port for the FTP data - where do we keep that information until we see the FTP data packet? There is currently no way to do that... 🤔

**Comment by egecetin** [comment]
For now we can only decide from if it is port 20 which is very rare case, until dynamic ports are supported.

**Comment by seladb** [comment]
port 20 is only for FTP control packets, no?
Or can it be used for FTP data as well?

**Comment by egecetin** [comment]
20 is for data, 21 for control

**Comment by seladb** [comment]
Oh you're right, my bad, sorry...

**Comment by egecetin** [comment]
Partially (static port only) FTP Data support added with #1126.
