### ISSUE TITLE
Have an option to allow TcpLayer & UdpLayer to always set the next layer as PayloadLayer

### ISSUE THREAD

**Issue by tigercosmos** [seladb/PcapPlusPlus#1152]
Maybe we can have an option for `TcpLayer` & `UdpLayer` to set the next layer always to be `PayloadLayer`

I have noticed that in certain cases, relying solely on port numbers for parsing RawPackets using PCPP library may not be ideal. There are situations where a customized port number is utilized for purposes other than the expected protocol (e.g. HTTP port can be any number). In such scenarios, it may be preferable to extract the `PayloadLayer` and allow the user to cast it to the appropriate layer as needed.

**Comment by seladb** [comment]
I can my answer into 2 parts:
1. Parsing up to a certain layer already exists - when calling the `pcpp::Packet` c'tor you can provide `parseUntil` or `parseUntilLayer` which will only parse up to that layer and leave the rest of the data as `PayloadLayer`. Please take a look here: https://github.com/seladb/PcapPlusPlus/blob/e96b741df40aa5e397916ab3c107ec2a57d37b8e/Packet%2B%2B/header/Packet.h#L72
2. The other part of casting `PayloadLayer` to a different layer is not currently possible. It will not be easy to implement because it will require to re-parse the data as a different layer, and then replace the existing `PayloadLayer` with the new layer. And what if `PayloadLayer` has multiple layers and not just one? 🤔

**Comment by tigercosmos** [comment]
1. ah, thanks, I don't know there is a constructor for doing this.

2. for casting `PayloadLayer`, I think `PayloadLayer` is already the last layer, so why is it possible to have multiple layers? In addition, I think `PayloadLayer` contains basically only raw payload (unparsed bytes), which we can move the payload bytes directly for constructing the new layer. 

btw, currently I just do in this way:
```cpp
httpLayer = new pcpp::HttpResponseLayer(payloadLayer->getData(), payloadLayer->getDataLen(), tcpLayer, packet.get());
 ```

**Comment by seladb** [comment]
> 2\. for casting `PayloadLayer`, I think `PayloadLayer` is already the last layer, so why is it possible to have multiple layers? In addition, I think `PayloadLayer` contains basically only raw payload (unparsed bytes), which we can move the payload bytes directly for constructing the new layer.

It depends on the packet. With HTTP it's usually 1 request/response on top of TCP, but consider SSL/TLS for example which can have multiple messages...

**Comment by tigercosmos** [comment]
I understand now. Regarding point 1, is it possible to prevent layer parsing specifically for UDP or TCP? It appears that we can only set the `parseUntil` option for a single layer type. What I'm aiming for is to extract the payload data from either TCP or UDP without having prior knowledge of the packet type.

**Comment by seladb** [comment]
Unfortunately it's not currently possible to define a list of `parseUntil` protocols, the constructor only supports one...

**Comment by seladb** [comment]
@tigercosmos should we close this issue?

**Comment by tigercosmos** [comment]
let's close it
