### ISSUE TITLE
Question regarding the drop of nanosecond precision timestamp

### ISSUE THREAD

**Issue by Teles1** [seladb/PcapPlusPlus#1189]
The nanosecond precision is lost while re-assembling a TCP stream. I needed to know the timestamp for when a portion of a given stream arrived and unfortunately the precision was lost. Was this a design decision or if a pull request comes in to change this to timespec for example would it get merged in? Thanks
https://github.com/seladb/PcapPlusPlus/blob/666e2927569c685fd69aaf3560322287676cabaa/Packet%2B%2B/src/TcpReassembly.cpp#L29

**Comment by seladb** [comment]
Hi @Teles1 ! I found the commit where it was changed: https://github.com/seladb/PcapPlusPlus/commit/2583f64ef62816a6a887c594e7aabb2b5482000a#diff-654f2a86f6954fcb6e711df2d4550f16028c3f79c08b2a7bc851dfa227dc37d2

As you can see, it was added when the packet timestamp became more accurate and changed from `timeval` to `timespec`. I assume we didn't want to change the `ConnectionData` and `TcpStreamData` structs and keep them backward compatible so we decided to just convert `timespec` back to `timeval`. 

However, I think it can be a nice change to deprecate `timeval` and move to a struct with higher precision. It can be either `timespec`  or a more C++11-style structure like `std::chrono::time_point`.

In order to stay backward compatible I'd keep the `timeval` properties in `ConnectionData` and `TcpStreamData`, mark them as deprecated and add new `timespec` / `std::chrono::time_point` properties. In the next version we can remove the `timeval` properties completely.

Would you consider implementing this change?

**Comment by Teles1** [comment]
Sure. Will do.

**Comment by seladb** [comment]
Fixed in https://github.com/seladb/PcapPlusPlus/pull/1591
