### ISSUE TITLE
Reassembling UDP packets

### ISSUE THREAD

**Issue by Idan-Neeman** [seladb/PcapPlusPlus#1195]
I have a pcap file that contains numerous UDP packets, some of which pass through IP fragmentation. I'm interested in using the IPDefragUtil to reassemble the fragmented UDP packets from this pcap file. However, I have a few questions.

Are there any performance considerations or limitations when dealing with a large number of fragmented UDP packets in a pcap file? Is there a recommended approach for handling such scenarios efficiently?
What about desegmentation (Transport layer) issues? Does anyone have experience with them?

**Comment by seladb** [comment]
> Are there any performance considerations or limitations when dealing with a large number of fragmented UDP packets in a pcap file? Is there a recommended approach for handling such scenarios efficiently?

There is one limitation I can think which is 500,000 packets that can be kept in memory at every given moment. This can happen if there are a lot of fragmented packets that are processed in parallel, for example:
```
Time = 0: got frag 1 of packet 1
Time = 1: got frag 1 of packet 2
...
Time = 500,000: got frag 1 of packet 500,000
Time = 500,001: got frag 1 of packet 500,001
...
```
In this example, in time 500,001 the data of packet 1 will be dropped.
Of course, for most practical usages something like this shouldn't happen. However, if it is a limitation for you, all you need is a small change in [`ipReassembly` initialization](https://github.com/seladb/PcapPlusPlus/blob/22c6c85130ececa0cd4f9367332b8142687722c4/Examples/IPDefragUtil/main.cpp#L107) - you can initialize it with `maxPacketsToStore = <ANY_NUMBER_YOU_WANT>`

Other than that I don't see any practical limitation.

> What about desegmentation (Transport layer) issues? Does anyone have experience with them?

Do you mean UDP desegmentation? As opposed to TCP, UDP desegmentation is very simple because UDP doesn't have sequences, ack numbers etc. so desegmentation is basically getting the payload of the UDP layer. Of course UDP doesn't guarantee delivery or correct packet order,  but these limitations are built into the protocol.

If you're interested in TCP reassembly, take a look at the [`TcpReassembly` util](https://github.com/seladb/PcapPlusPlus/blob/master/Examples/TcpReassembly/README.md)

**Comment by seladb** [comment]
@Idan-Neeman should we close this issue or keep it open?

**Comment by Idan-Neeman** [comment]
> @Idan-Neeman should we close this issue or keep it open?

Close 🙏 Thanks a lot!
