### ISSUE TITLE
Crash(segment fault) and memory leak for Packet++Test on master branch with CentOS7.9 X64 platform

### ISSUE THREAD

**Issue by wangchong2023** [seladb/PcapPlusPlus#1200]
cmake version 3.27.4
![image](https://github.com/seladb/PcapPlusPlus/assets/127951479/43a386a0-017d-49c9-8973-9f76fbc57e59)
![image](https://github.com/seladb/PcapPlusPlus/assets/127951479/ec571ebe-48ce-421e-92be-520d45d9e4b3)
![image](https://github.com/seladb/PcapPlusPlus/assets/127951479/7847d5be-6337-4ef4-92ff-473ea8627490)

**Comment by seladb** [comment]
@wangchong2023 there is a known issue with MemPlumber (that checks for memory leaks) in CentOS, that's why we disabled it in CI (by running `Packet++Test -s` (Skip memory leak check):
https://github.com/seladb/PcapPlusPlus/blob/399afa576c690d642e83cd1730172a4bb9b61420/.github/workflows/build_and_test.yml#L64
