### ISSUE TITLE
PcapSplitter Doesn't Write Nanosecond

### ISSUE THREAD

**Issue by wKavey** [seladb/PcapPlusPlus#1287]
Hey all! Love this library and it's many useful tools.

However, I hit one snag when using the example `PcapSplitter` utility. Even though it seems like I am compiling with `PCAP_TSTAMP_PRECISION_NANO` -- my output pcaps seem to be stripped of nanoseconds which were present in the input file.

Is there anything special I need to do in order to enable preservation of nanoseconds?

**Comment by egecetin** [comment]
Maybe related with #645 or #664.

- What is your file format `pcap` or `pcapng`?
- What is your `libpcap` version (or maybe `WinPcap`)?

**Comment by wKavey** [comment]
- The format is `pcap`, not `pcapng`. They have the correct nanosecond-support magic number (`0xa1b23c4d`) in the header.
- `libpcap` seems to be...
   - `libpcap-devel-1.8.1-10.3.1.x86_64`
   - `libpcap1-1.8.1-10.3.1.x86_64`

Similarly to #664 I took a quick look in `Pcap++/src/PcapFileDevice.cpp` at `PcapFileWriterDevice` and stumbled on `pcap_open_dead_with_tstamp_precision` -- however the below change isn't sufficient.


```diff
@@ -619,7 +622,7 @@ bool PcapFileWriterDevice::open()
        m_NumOfPacketsNotWritten = 0;
        m_NumOfPacketsWritten = 0;

-       m_PcapDescriptor = pcap_open_dead(m_PcapLinkLayerType, PCPP_MAX_PACKET_SIZE);
+       m_PcapDescriptor = pcap_open_dead_with_tstamp_precision(m_PcapLinkLayerType, PCPP_MAX_PACKET_SIZE, PCAP_TSTAMP_PRECISION_NANO);
        if (m_PcapDescriptor == nullptr)
        {
                PCPP_LOG_ERROR("Error opening file writer device for file '" << m_FileName << "': pcap_open_dead returned NULL");
```

However this seems to incorrectly adjust the nanosecond portion in packets.

Pre-split:  ```20240116-04:03:19.380540082```
Post-split:  ```20240116-04:03:19.000380540```

I'd imagine there is some more work that would be needed in the `PcapFileWriterDevice::writePacket(...)` to send the time as nanos and not just (old_micros / 1000).

**Comment by seladb** [comment]
@wKavey I'm sorry for the late reply. PcapPlusPlus uses libpcap's `pcap_dump` to write packets to file:
https://github.com/seladb/PcapPlusPlus/blob/334d72bb5649b7e2ead55f4fb7744d7fbcc2992f/Pcap%2B%2B/src/PcapFileDevice.cpp#L566

Unfortunately `pcap_dump` only supports microseconds precision:

https://github.com/the-tcpdump-group/libpcap/blob/9e31cdf2d83a7540d5ca129fbd99ee41fdaf41e9/pcap/pcap.h#L774

It accepts `pcap_pkthdr` which has a timestamp of time `timeval`:

https://github.com/the-tcpdump-group/libpcap/blob/9e31cdf2d83a7540d5ca129fbd99ee41fdaf41e9/pcap/pcap.h#L294

That's why PcapPlusPlus needs to convert `timespec` (nanosec precision) to `timeval` (microsec precision):
https://github.com/seladb/PcapPlusPlus/blob/334d72bb5649b7e2ead55f4fb7744d7fbcc2992f/Pcap%2B%2B/src/PcapFileDevice.cpp#L564

**Comment by seladb** [comment]
@wKavey what should we do with this issue?

**Comment by seladb** [comment]
@wKavey I'm closing this issue for now, please reopen it if needed
