### ISSUE TITLE
Memory Leak when parseNextLayer is used

### ISSUE THREAD

**Issue by JasMetzger** [seladb/PcapPlusPlus#1449]
### Bug description

Capturing on a device using
    ` device_->startCapture(onPacketArrivesCallback, myclassobj)`

When RawPacket is read it is parsed up to the IPLayer. 
```
     pcpp::Packet ppkt;
     ppkt.setRawPacket(rawPacket, false, pcpp::IP);
```

Later we do this to get the ports if either UDP or TCP is the next layer:
```
                        pcpp::IPv4Layer* ipv4Layer = ppkt.getLayerOfType<pcpp::IPv4Layer>();
			if (ipv4Layer)
			{
				ipv4Layer->parseNextLayer();
				pcpp::Layer* nextlayer = ipv4Layer->getNextLayer();
				pcpp::ProtocolType nextprotocol = nextlayer->getProtocol();

				if (nextlayer && nextprotocol == pcpp::UDP)
				{
					pcpp::UdpLayer* udplayer = (pcpp::UdpLayer *)nextlayer;	
					uint16_t udpsrcport = udplayer->getSrcPort();
					uint16_t udpdstport = udplayer->getDstPort();
				}
				else if (nextlayer && nextprotocol == pcpp::TCP)
				{
                                        pcpp::TcpLayer* tcplayer = (pcpp::TcpLayer*)nextlayer;
					uint16_t tcpsrcport = tcplayer->getSrcPort();
					uint16_t tcpdstport = tcplayer->getDstPort();
                                 }
```

When I run this feeding it data from a tcpreplay, the memory utilization of the process grows and grows unbounded. If I don't parseNextLayer, the memory utilization is stable. 

Should the application be deleting the "nextLayer" object or will it vanish when the parsed Packet goes out of scope? I have made the parsePacket an automatic variable that goes out of scope as above and also has a private member data that is reused but the memory leak shows either way. 

### PcapPlusPlus versions tested on

v23.09

### Operating systems tested on

Linux

### Compiler version

GCC 11.4.0

### Packet capture backend (if applicable)

libpcap

**Comment by seladb** [comment]
@JasMetzger yes, this is an expected behavior. When a `pcpp::Packet` is created, it keeps track of which layers it generated so it can delete them when the packet is destroyed.

When you call `layer.parseNextLayer()` outside of the `pcpp::Packet` creation context, the packet isn't aware that this layer was created so it won't delete it.

This is to support a scenario where a packet is created with existing layers created by the user, in which case it should delete those layers.

You can choose between the following options:
- Call `ppkt.setRawPacket(rawPacket, false, pcpp::UnknownProtocol, pcpp::OsiModelTransportLayer)` to parse up to L4 (TCP/UDP) and then you don't need to manually parse TCP/UDP
- Call `ipv4Layer->parseNextLayer()` but delete `ipv4Layer->getNextLayer()` manually

**Comment by JasMetzger** [comment]
Thanks for the quick response. I did figure that I would have to manually delete it.  When I put

`delete nextlayer
`
after the if/else clause and something went wrong when I did this---an exception. Is there a time I should do this?

I was able to work-around by doing this

`ppkt.setRawPacket(rawPacket, false, pcpp::UDP | pcpp::TCP);
`
The nature of the defined values seem to lend themselves to OR-ing. It seemed to work. Can I OR these definitions?

Thanks again!

**Comment by seladb** [comment]
You can delete this layer outside of the context of the packet.

But as I mentioned, a better way would be to parse the packet up to the transport layer:
```cpp
ppkt.setRawPacket(rawPacket, false, pcpp::UnknownProtocol, pcpp::OsiModelTransportLayer)
```

**Comment by JasMetzger** [comment]
That was probably why it freaked out; I deleted the layer before the packet was freed. If I use the OsiModelTransportLayer, what besides UDP and TCP will it parse? Thanks for you help.

**Comment by seladb** [comment]
If you use `OsiModelTransportLayer` it'll parse all of the transport layer protocols, which are mostly UDP and TCP, but may also be other protocols such as IPsec, GTP and a few others.

Using OR with `TCP|UDP` will work in v23.09, however it will stop working in the next release of PcapPlusPlus (which is planned for a few months from now) because we changed the underlying protocol values

**Comment by JasMetzger** [comment]
Thanks again. I will use the OsiModelTransportLayer method then.
