### ISSUE TITLE
Potential memory leak in PointerVector pushBack, if internal vector reallocation fails.

### ISSUE THREAD

**Issue by Dimi1010** [seladb/PcapPlusPlus#1465]
In large parts of the code base, `PoiterVector::pushBack()` is being used as `pVector.pushBack(new T(...));`. With the current `pushBack` implementation, if the internal call to `m_vector.push_back()` requires a reallocation and fails, the pointed element is leaked in those cases. 

Opening an issue instead of directly addressing it in a PR, because there are a couple possible ways to address it:
- Assume ownership is transferred at the `pushBack` call and clean up the element on error.
- Provide a flag `cleanupOnError` to let the call site determine if the vector should handle the cleanup or the call site.
- Assume the call site will handle cleanup of the pointed element on exception and don't do anything in the vector itself.

**Comment by seladb** [comment]
@Dimi1010 I'd vote for option 2. The flag can have a default value of `false` so it's backward compatible

**Comment by seladb** [comment]
> @Dimi1010 I'd vote for option 2. The flag can have a default value of `false` so it's backward compatible

@Dimi1010 I take it back. Thinking about it again, the main use of `PointerVector` is to take ownership of the pointers it contains, and free them when they're not used anymore. If `pushBack()` fails, the default behavior should be to free the pointer because the caller assumes they no longer need to handle it.

**Comment by Dimi1010** [comment]
Fixed in #1487
