### ISSUE TITLE
Parsing packets captured from Mac OS X rvi interface doesn't work

### ISSUE THREAD

**Issue by axasoft** [seladb/PcapPlusPlus#160]
On Mac OS X High Sierra, rvi interface (https://useyourloaf.com/blog/remote-packet-capture-for-ios-devices/) seems to erroneously set the link type ETHERNET, while in reality there's no ethernet frame. I'm not familiar with pcap -library, so I cannot say if this a bug in OS X, or in libpcap.

Anyway, with the following kludge I managed to get IPv4 packets to my application, but it would be cool if this issue is fixed properly:
```
diff --git a/Packet++/src/Packet.cpp b/Packet++/src/Packet.cpp
index f86100f..10b9c00 100644
--- a/Packet++/src/Packet.cpp
+++ b/Packet++/src/Packet.cpp
@@ -50,6 +50,11 @@ void Packet::setRawPacket(RawPacket* rawPacket, bool freeRawPacket, ProtocolType
                return;
 
        LinkLayerType linkType = m_RawPacket->getLinkLayerType();
+       if (linkType == LINKTYPE_ETHERNET && (*m_RawPacket->getRawData() == 0x45))
+       {
+               // printf("Faking LINKTYPE\n");
+               linkType = LINKTYPE_RAW;
+       }
 
        if (linkType == LINKTYPE_ETHERNET)
        {

```

**Comment by seladb** [comment]
Thanks for filing this issue. The reason packets are parsed as `LINKTYPE_ETHERNET` and not `LINKTYPE_RAW` is because currently I don't have a way to differentiate between "regular" and RVI interfaces. Please take a look in this code for example:
https://github.com/seladb/PcapPlusPlus/blob/bc5f99496ce0bec824045c54fbecdd738edc0723/Pcap%2B%2B/src/PcapLiveDevice.cpp#L132

If I had a way to identify an interface as RVI I could create the `RawPacket` instance with `LINKTYPE_RAW` type. I  googled briefly on how to find if an interface is RVI but I couldn't find anything, except for maybe check the interface name (`rvi[X]` is the standard name for RVI interfaces). If looking at the name is the only way maybe we can dig deeper into that,. Can you think of other options?

**Comment by axasoft** [comment]
I think you can use pcap_datalink to get the correct link type:

```diff --git a/Pcap++/src/PcapLiveDevice.cpp b/Pcap++/src/PcapLiveDevice.cpp
index 7dd7135..0ace30a 100644
--- a/Pcap++/src/PcapLiveDevice.cpp
+++ b/Pcap++/src/PcapLiveDevice.cpp
@@ -266,6 +266,19 @@ pcap_t* PcapLiveDevice::doOpen(const DeviceConfiguration& config)
                pcap_close(pcap);
                pcap = NULL;
        }
+       if (pcap)
+       {
+               int dlt = pcap_datalink(pcap);
+               const char *dlt_name = pcap_datalink_val_to_name(dlt);
+               if (dlt_name)
+               {
+                       printf("link-type %u: %s (%s)\n", dlt, dlt_name, pcap_datalink_val_to_description(dlt));
+               }
+               else
+               {
+                       printf("link-type %u\n", dlt);
+               }
+       }
        return pcap;
 }
 
```

For RVI interfaces, the code  prints "link-type 12: RAW (Raw IP)"

**Comment by seladb** [comment]
I agree, that makes a lot of sense. Would you like to make the change and submit a PR?

**Comment by axasoft** [comment]
PR submitted.

**Comment by seladb** [comment]
Thank you so much! I'll take a look later today or tomorrow and merge it into master

**Comment by seladb** [comment]
I've merged the PR. I'll add some unit-tests later today and then close the issue

**Comment by seladb** [comment]
I enhanced your code to include any kind of link-type: https://github.com/seladb/PcapPlusPlus/commit/7ab50eb742ca6c874715bd3da55fc638a92319af

Thank you so much for your contribution!

I'll close the issue now, please reopen it if you see any issue
