### ISSUE TITLE
Filter for IPv4 Protocols

### ISSUE THREAD

**Issue by austin-millan** [seladb/PcapPlusPlus#165]
Hello @seladb,

First off I just want to say thank you for starting this awesome library. It's fast, simple to setup, and the documentation is great.

This issue is on the topic of packet filtering. The Pcap++ filter objects ([here](https://seladb.github.io/PcapPlusPlus-Doc/Documentation/a01230.html)) seem to cover a subset of [BPF](https://en.wikipedia.org/wiki/Berkeley_Packet_Filter) options, so there's many use-cases that would be impossible to achieve with Pcap++.

For example, in my case I would like to filter packets for specific [IPv4 protocols](https://en.wikipedia.org/wiki/List_of_IP_protocol_numbers) (protocol 47). The [ProtoFilter](https://seladb.github.io/PcapPlusPlus-Doc/Documentation/a01282.html) object kind of stops short here, since it only allows filtering for TCP, UDP, ICMP, VLAN, IPv4, IPv6, ARP, Ethernet. I'm looking to filter GRE packets, IP protocol 47. 

Any help here would be appreciated

**Comment by seladb** [comment]
Thanks for the kind words and feedback!

When I wrote packet filtering in PcapPlusPlus (long time ago :) ) I implemented only the filters I thought would be useful for most people.  I didn't implement all possible filters because that would have take me a very long time. But I'm very open to implement more filters as needed

Regarding your ask to filter GRE packets - I'm not sure this is supported by BPF filters. Protocol filter is only applicable to a certain list of protocols:

> proto
    qualifiers restrict the match to a particular protocol. Possible protos are: ether, fddi, tr, wlan, ip, ip6, arp, rarp, decnet, tcp and udp.

Please let me know if I'm missing anything

**Comment by seladb** [comment]
Please let me know what would be the next step. Should we keep the issue or close it?

**Comment by austin-millan** [comment]
I think it might be supported by the BPF program filters if the protocol # is specified in the filter.

So something like `ip proto 47` or `protochain GRE` (syntax [here](http://www.biot.com/capstats/bpf.html)).

**Comment by seladb** [comment]
That's a good point, definitely worth to try. Would you mind trying, making the code change and submit a PR?

**Comment by seladb** [comment]
I pushed the issue to `master`. I'm closing the issue now, please reopen if needed
