### ISSUE TITLE
Getting issue to use IPDeregmentation utility in DPDK Bridge Example application

### ISSUE THREAD

**Issue by Muhammad-Akram** [seladb/PcapPlusPlus#235]
While merging the code of IPDefragment Util in DpdkExampleBridge application, application is not able to concatenate two fragments into one rather giving an error 
**"Couldn't append 2092 bytes to mbuf"**
Need help about where mempool initialization can be done using PcapPlusPlus examples. Thanks

![image](https://user-images.githubusercontent.com/40422137/64425840-65b56700-d0c6-11e9-95b4-e2ab09012b57.png)

**Comment by seladb** [comment]
As you already figured out, the reason for this error is that DPDK mbuf can't go over the size of `RTE_MBUF_DEFAULT_BUF_SIZE` which is 2048 bytes. In order to work with packets larger than that DPDK provides a mechanism to chain mbufs but this mechanism is not yet supported in PcapPlusPlus.

You can try to create a mempool with a larger size, but I can't guarantee it would work as I've never tried it. The code you need to change is here:

https://github.com/seladb/PcapPlusPlus/blob/fe2d92c3f5f3b171758cc096870b95961aeeac1c/Pcap%2B%2B/src/DpdkDevice.cpp#L334

Please let me know if this change works

**Comment by Muhammad-Akram** [comment]
Thank you Seladb for the help. I was not able to locate mempool creation. It worked for me.

**Comment by seladb** [comment]
I'm glad to hear! can we close this issues?

**Comment by seladb** [comment]
I'm closing this issue now. Please reopen it if needed
