### ISSUE TITLE
Dropping Packets Advice

### ISSUE THREAD

**Issue by Dysl3xik** [seladb/PcapPlusPlus#249]
This is a request for help / guidance, not a bug per say. I am unsure of a better place to put this at.

I have been working with PCPP for a while now. I have been able to use it to successfully capture packets reliably while doing testing and development, and have now moved on to integrating it into my larger application.

The input stream is something like 30Mbits/sec as a baseline.

Now that I have integrated it into my major project I am consistently missing packets. I can run the software and test software at the same time and the test software seems to reliably capture ALL packets while the integrated one will occasionally miss a packet. This happens even with both sides are configured identically and running the same backing capture code. Getting the final captured/dropped counts using the stats functions does not seem to report anything reliable in windows so I have given up on that. 

My software is running multiple threads so I can see how some contention could happen but I am nowhere near approaching my CPU limits or anything like that so that doesn't quite add up for me. The only other difference I can figure is that the REAL app is actively communicating with the device I am trying to capture from WHILE capturing. While the test software is just "listening in" I don't know if running TCP with ASIO while trying to capture in the same program can lead to issues but that is my setup. 

I have tried adjusting the pcap start config with the some of the following options:
```
//config.mode = pcpp::PcapLiveDevice::DeviceMode::Normal;
//config.packetBufferTimeoutMs = 1;
//config.packetBufferSize = 20000000;
````

Normal mode should be all I need but I have tried promiscuous too and that doesn't help.
Setting the buffer timeout actually leads to MORE missed packets, but lessens CPU load
The buffer size I have ranged from 20MB all the way to 200MB it seems to help when its higher than default but going all the way to 200 makes no difference.

I am unsure what else to try here to help with things. My callback function in both cases is just saving to a file I am not processing and holding up the thread for long periods.

Do anyone have any ideas or suggestions on things to check or try out?

P.S. I am confirming missing packets by opening the capture backup in wireshark and seeing ACKS for unseen segments and segment not captured messages.

**Comment by seladb** [comment]
Thanks for providing these details. While it's quite difficult to debug this issue without actually seeing your application, here are a few things I have in mind to try to narrow down the possible root causes:

- You mentioned you're writing packets to a file. Disk I/O can be very expensive in terms of performance. I'd suggest testing the same code without writing to disk. You can keep a packet counter in memory to see if packets are still being dropped or not. If this is the issue you can consider making less writes, for example write to disk every X packets or put the packets in a queue and have another thread/process to do the actual writing
- You didn't mention if you're parsing the packets or not. If you are, try to run the same code without full parsing. You can use `pcpp::Packet::Packet(RawPacket* rawPacket, ProtocolType parseUntil)` for partial parsing
- Try to disable some of the other threads, just for testing purposes. If this is the root cause then we need to dig deeper to understand why this is an issue
- Try to lower the packet rate and observe what is the threshold for loosing packets

**Comment by Dysl3xik** [comment]
Not surprisingly this ended up being my own stupid fault. I was accidentally continuously setting the capture filter in my integrated version. 

It is 100% allowed to change the filter mid capture, BUT, every time you change it will toss packets currently in the buffer. This was ultimately leading to my missing packets!

**Comment by seladb** [comment]
Thanks for the update, I'm glad you found the root cause so quickly
