### ISSUE TITLE
TcpReassembly, memory leakage

### ISSUE THREAD

**Issue by gx740** [seladb/PcapPlusPlus#250]
When the session is removed the `flowKey` is put into `m_ClosedConnectionList` map.
Unfortunately this map never clears.

**Comment by seladb** [comment]
Yes, this is probably an issue in high scale.

On one hand we need to keep a list of closed connections in case we see a packet that comes after the FIN packet (which happens sometimes due to network issues). On the other hand we probably don't need to keep it forever. 

When I built this feature I was thinking whether to build a cleanup mechanism or not and I've decided to postpone it until the demand comes. This mechanism should be carefully designed to avoid performance overhead.

Another approach might be moving the cleanup responsibility to the user by exposing a method to do so. But this will complicate the API and will make TcpReassembly more difficult to use.

Please let me know what you think.

**Comment by seladb** [comment]
@gx740 PR is merged and pushed to `master`, please let me know if we can close this issue

**Comment by gx740** [comment]
You can close this PR.
