### ISSUE TITLE
Submit FreeBSD port for PcapPlusPlus

### ISSUE THREAD

**Issue by rickyzhang82** [seladb/PcapPlusPlus#268]
I'm not a legal expert. But it seems that **The Unlicense** is compatible with **FreeBSD license**.

So I create this issue to discuss the on-going work to submit FreeBSD port for PcapPlusPlus to upstream.

Here is [the FreeBSD instruction for porters](https://www.freebsd.org/doc/en_US.ISO8859-1/books/porters-handbook/)

**Comment by seladb** [comment]
Regarding the license - please see issue #247 - I plan to change PcapPlusPlus license to a more "standard" one, probably either BSL or MIT.

The change will probably happen in the next official release. I'm guessing FreeBSD port will also need an official release so maybe that can work for us. Please let me know what you think

**Comment by rickyzhang82** [comment]
That’s correct. We need an official release for FreeBSD port file to download the source from.

There should be very minimal work left to do.  No patches will be needed. For you,

1. Change to OSI approved license. Preferable - BSD or MIT.
1. Make an official release.

**Comment by seladb** [comment]
I have [this project](https://github.com/seladb/PcapPlusPlus-Deploy) to package and release new versions. It does different packaging according to the OS / platform. I need to add the latest supported platforms which are FreeBSD and Visual Studio 2017, 2019.

Usually when I create a new release I do extensive testing to make sure the package, examples and tests work well on all platforms. I also prepare the relevant documentation such as release notes etc. That's why I have only 1-2 releases a year...

I'm planning to start working on the next release soon, but it'll probably take me at least a few weeks

**Comment by rickyzhang82** [comment]
No rush to this process. According to [the section in porter's handbook](https://www.freebsd.org/doc/en_US.ISO8859-1/books/porters-handbook/slow-sources.html), FreeBSD ports usually require a source package files.

Once you make a release including all src, I will try to write a FreeBSD port file in your deploy repo.

**Comment by seladb** [comment]
I just released [v19.12](https://github.com/seladb/PcapPlusPlus/releases/tag/v19.12). The source files are [included in the release](https://github.com/seladb/PcapPlusPlus/archive/v19.12.tar.gz).

If you'd like to work on FreeBSD port file that'll be of great help.

**Comment by rickyzhang82** [comment]
Sure, I will take a look. 

I'm busy with `TcpSorter` implementation in my spare time. I will find some time to give a try to write a sample port files.

**Comment by seladb** [comment]
@rickyzhang82 any progress on that?

**Comment by seladb** [comment]
I'll close this issue for now since there is not much progress. Please reopen if you're planning to work on this
