### ISSUE TITLE
issue in matchPacketWithFilter

### ISSUE THREAD

**Issue by silviucpp** [seladb/PcapPlusPlus#284]
Hello,

Method `IPcapDevice::matchPacketWithFilter(std::string filterAsString, RawPacket* rawPacket)` assume that first layer into the packet is of type `pcpp::LINKTYPE_ETHERNET` which is not true.

For example in case you capture on linux on "any" interface the first layer is of type: `LINKTYPE_LINUX_SLL`

I think you should use instead the `rawPacket->getLinkLayerType()` method

Silviu

**Comment by seladb** [comment]
Yes you're right, currently only Ethernet is supported. I'm not how well BPF filters are working with SLL, do you have some experience with that?

BTW, instead of using `IPcapDevice::matchPacketWithFilter()` you should use [BPFStringFilter](https://github.com/seladb/PcapPlusPlus/blob/e0b0d6cd75cdbf4009ac15c9fb474da46786838d/Pcap%2B%2B/header/PcapFilter.h#L115) which is more efficient

**Comment by silviucpp** [comment]
Hello,

It's working fine. I fixed the problem on my side by setting the proper layer (to match the one from the capture device) and seems ok.

**Comment by seladb** [comment]
awesome ,thanks! Can we close this issue?

**Comment by silviucpp** [comment]
Yes. in case you are not interested in fixing this for me it's fine!

Silviu

**Comment by seladb** [comment]
Closing it for now. If similar requests will come up in the future we can consider making this change
