### ISSUE TITLE
Bad tcp payload size on malformed tcp packet

### ISSUE THREAD

**Issue by prus1337** [seladb/PcapPlusPlus#315]
TcpLayer::getLayerPayloadSize() return bad size on malformed tcp packet.
Pcap example (1 tcp packet):
[pcpp.malformed.packet.zip](https://github.com/seladb/PcapPlusPlus/files/3923184/pcpp.malformed.packet.zip)

**Comment by seladb** [comment]
thanks, I'll take a look and let you know

**Comment by seladb** [comment]
I'm not sure it's really a bug. As you mentioned the packet is malformed and the TCP header length is 32 bytes which is more than the total packet size which is 30 bytes. `TcpLayer::getLayerPayloadSize()` looks at the total size of the packet minus the header length and that's why it gives a size of `-2`

**Comment by prus1337** [comment]
> 
> 
> I'm not sure it's really a bug. As you mentioned the packet is malformed and the TCP header length is 32 bytes which is more than the total packet size which is 30 bytes. `TcpLayer::getLayerPayloadSize()` looks at the total size of the packet minus the header length and that's why it gives a size of `-2`

Thanks. May be wish it is needed to add isPacketValid() check malformed packets?

**Comment by seladb** [comment]
It's not very straight forward to add such a check because malformed packet can happen because of a variety of reasons, your example is just one of them

**Comment by seladb** [comment]
I'll close this issue now, please reopen if needed

**Comment by prus1337** [comment]
Thanks for help
