### ISSUE TITLE
[New Feature Proposal] Add an explicit flush in PcapFileDevice

### ISSUE THREAD

**Issue by rickyzhang82** [seladb/PcapPlusPlus#338]
When I write packets into disk through `PcapFileDevice`, the content doesn't flush into disk until `close()` is invoked. This causes out-of-memory problem in memory limited router where many connections have long lasting traffic like streaming or downloading file.

I'd like to add an explicit `flush()` call in `PcapFileDevice` so that the packets can be written to disk in a timely manner under user's discretion. 

Please let me know if you approve the idea.

**Comment by seladb** [comment]
I'm not sure that `flush()` will be easy to implement because this API is not exposed by WinPcap/libpcap. When I implemented [append mode](https://github.com/seladb/PcapPlusPlus/blob/ea1d380ac9487c48af7c32ca3d67ccfc7fa83842/Pcap%2B%2B/header/PcapFileDevice.h#L287) I faced the same issue and had to [copy code from libpcap](https://github.com/seladb/PcapPlusPlus/blob/ea1d380ac9487c48af7c32ca3d67ccfc7fa83842/Pcap%2B%2B/src/PcapFileDevice.cpp#L468) in order to achieve that.

A workaround for flushing can be closing the file and reopening it in Append mode, however I wouldn't recommend making that an API of its own (because it's not really flushing).

**Comment by rickyzhang82** [comment]
I thought the proposed `flush` method just did the following like you did in the `close`.

https://github.com/seladb/PcapPlusPlus/blob/ea1d380ac9487c48af7c32ca3d67ccfc7fa83842/Pcap%2B%2B/src/PcapFileDevice.cpp#L544-L554

My sample program did close file and thus flush the content once the file descriptor reach maximum number. But it is already too late as I said.

**Comment by seladb** [comment]
Oh you're right it's my bad, I don't remember adding that code 😊

In that case please feel free to add this to the API

**Comment by rickyzhang82** [comment]
See PR #340
