### ISSUE TITLE
Source tar.gz seems corrupted

### ISSUE THREAD

**Issue by russkel** [seladb/PcapPlusPlus#370]
When downloading the Linux tarball (https://github.com/seladb/PcapPlusPlus/releases/download/v19.12/pcapplusplus-19.12-source-linux.tar.gz) I am getting:

```
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors
```

Weirdly enough if I gunzip and then extract with tar it seems to open. Note this does not happen with other tar.gz files I have encountered.

**Comment by seladb** [comment]
Thanks for reporting this issue!

There was indeed a problem with all of the Linux and FreeBSD tarballs, probably because of the [Cirrus CI packaging script I'm using](https://github.com/seladb/PcapPlusPlus-Deploy/blob/master/.cirrus.yml). I suspect that when I downloaded the tarball files from Cirrus CI server (for example [here](https://cirrus-ci.com/task/6018227821346816)) there was some issue with the files.

I'll look further into it towards the next release but in the meantime I manually fixed and uploaded all of the Linux and FreeBSD files and they should work now.

Please reopen the issue and let me know if you still see the problem.

**Comment by russkel** [comment]
Thanks!
