### ISSUE TITLE
Incorrect behavior in TcpReassembly with pcaps when the stream is unidirectional and missing data is encountered

### ISSUE THREAD

**Issue by dwalthour** [seladb/PcapPlusPlus#405]
When the TCP stream is unidirectional and a gap in the pcap is encountered, TcpReassembly begins buffering the fragments of the stream, but since there is no point at which the other side sends, the fragment buffering continues unabated until the sequence numbers loop at 2^32 and the reassembly begins replaying fragments in the wrong order.  Additionally, since the fragment container is a vector, 1) long linear searches are performed to find packets to insert into the stream, and 2) the calls to erase in the fragment vector (typically with a length on the order of 2^22 or more, at this point) begin taking as much as 80% of the CPU to do memmove calls.

The proposed solution is to: 1) track the ack_sequence in addition to the sequence so that the unidirectional sender can tell that the ack has been received and that TcpReassembly::checkOutOfOrderFragments() can be called to send the missing data message, and 2) change the vector to a map in order to keep them sorted by sequence and allow the linear searches to be cut short by knowing which range of sequences are of interest (the first linear search in TcpReassembly::checkOutOfOrderFragments()) or reduced to a call to upper_bound() on the map (the second linear search in TcpReassembly::checkOutOfOrderFragments()) and also so that erase becomes an O(1) operation.

**Comment by seladb** [comment]
I'm sorry for the late response.

Indeed, the TCP reassembly feature wasn't designed for unidirectional streams with missing data.

Regarding your suggestions:

1. Looking at the ack sequence will not solve this because a missing packet doesn't really mean it wasn't seen be the client/server (otherwise the client/server would ask to retransmit it). The packet is only missing in the packet stream you're looking at, probably because of a packet drop or similar issue. Packet can also get reordered due to network issues. So even the ack number suggests the client/server already saw the packet, you may still see it later in your stream. The current implementation assumes that a missing packet is really missing only when it sees the first data packet coming from the other side. Of course this may not be true in some cases, but I had to decide when to clean the missing packet buffer, so I implemented the same mechanism that Wireshark has

2. Implementing the list as a map is an interesting idea, we just need to make sure that in the most common use-case, which is when the list size is pretty short we still get similar or better performance

What I'd suggest to overcome the issue you're describing is to add a configuration parameter to `TcpReassemblyConfiguration` which tells what is the max size  (or max count) the missing packet buffer can contain. By default it can be "unlimited" but if assigned a value, this value can be used to clean the out-of-ordered buffers that contain too much data. Please let me know what you think

**Comment by seladb** [comment]
@dwalthour please let me know what you think

**Comment by dwalthour** [comment]
Sorry about my delay in getting back to you.  I did put in such a configuration parameter that placed a max count of missed messages, but then I pulled it back out and put the ack sequence number checking in place (described earlier) instead because it worked better for me.  My situation is using tcpdump to capture a unidirectional tcp stream that has a high volume of traffic.  The tcp traffic is being received by the application just fine but tcpdump can't always keep up so it drops incoming packets while busy writing to the file.  By checking the ack sequence number, I can see that the application that actually received the traffic got it but that its missing from the pcap so just mark it as missing and move on in the playback.  With this logic in place, the list of fragments never grows very long so keeping it as a vector is not so punitive as it is when the fragment list gets huge by not recognizing the missing packets.  However, the map is faster on the processing when the list gets longer.  If you aren't interested in the ack methodology, I am good with the config parameter you suggest because it does solve the problem, but I may keep the ack-based version for my own use.  I'm happy to push this to a branch if you want to examine my version.

**Comment by seladb** [comment]
Thanks @dwalthour ! please create a PR and I'll review the code

**Comment by dwalthour** [comment]
Sorry for the slow turnaround on this.  Somehow life is getting in the way more these days...
For some reason, I am not doing something right in making this pull request.  I am getting this:
$ git push origin TcpReassemblyImproveSpeedCheckAckSeqNo
Username for 'https://github.com': dwalthour@gmail.com
Password for 'https://dwalthour@gmail.com@github.com': 
remote: Permission to seladb/PcapPlusPlus.git denied to dwalthour.
fatal: unable to access 'https://github.com/seladb/PcapPlusPlus.git/': The requested URL returned error: 403

**Comment by seladb** [comment]
have you forked the repo first?

If not, you should fork it first - just hit the "Fork" button in the upper right corner:

![image](https://user-images.githubusercontent.com/9059541/77222384-d1659b80-6b0f-11ea-88e8-fada09eb9f1d.png)

Then you can push code to the forked repo and when you're done just create a PR

**Comment by dwalthour** [comment]
25 years a professional programmer, have used git enterprise for years now, and I still have to have my hand held because this is the first time I have ever attempted  to contribute to an open source project :grin: 
Thanks for the help! PR #413

**Comment by dwalthour** [comment]
didn't mean to close this

**Comment by seladb** [comment]
@dwalthour any update on this?

**Comment by dwalthour** [comment]
yes, i made a PR and was about to post here about this and came to the conclusion (which I think you already had), that while my solution fixes my problems, it it not general fix and breaks other things.  So I stepped back.  Now, I am in agreement that your counter idea is probably the best solution without disrupting other behaviours of the library.  I will pull that together and create another PR.

**Comment by seladb** [comment]
sure, thank you. Please create the PR and I'll review it

**Comment by seladb** [comment]
I'd like to follow up on this. Have you made any progress on this PR?

**Comment by seladb** [comment]
@dwalthour I'll close this for now, please reopen if needed

**Comment by LeonBuikstraFox** [comment]
Hi; I'd like to re-open this issue since I've run into the same problem. I'm currently working on a PR to implement your suggestion from the 6th of March. The code is here: https://github.com/LeonBuikstraFox/PcapPlusPlus/tree/fragment_limit_config , but I still need to get it through the CI steps. (should pass tests etc. since the default behaviour is completely unchanged)

I've noticed that even with the configuration option set, the number of stored fragments does not always go to zero if there was a period of very messy traffic, so maybe it would be a good idea to also have a way to clean up badly outdated fragments that will never get matched again, but the configuration at least allows the user to configure how bad the unmatched fragment count is allowed to get.

**Comment by seladb** [comment]
Thanks for opening the PR! I just reviewed and added a few comments

**Comment by LeonBuikstraFox** [comment]
Thanks! I'll get on them ASAP. It also seems the new unit test doesn't work on Appveyor because it can't open the pcapfile (I used editcap to modify "one_tcp_stream.pcap"), even though it worked fine under Linux. I do have a Windows 10 machine available so I'll try recreating the pcap file on that one but it might take a while.

**Comment by seladb** [comment]
thank you so much @LeonBuikstraFox for working on this!

From [Appveyor logs](https://ci.appveyor.com/project/seladb/pcapplusplus/builds/35986772/job/q2qaxrum9w0j9f9p) it seems that at least in Visual Studio there are build errors, probably because you're using `<limits>` which might not be fully supported.

![image](https://user-images.githubusercontent.com/9059541/97528419-f3a77d80-196a-11eb-955b-905a4aec2301.png)

**Comment by seladb** [comment]
Merged #538

**Comment by LeonBuikstraFox** [comment]
Happy to see you found out why the pcap file wouldn't open. Sorry for missing the final bits of the pull request, but thanks so much for the fast responses and finishing it the PR!

**Comment by seladb** [comment]
> Happy to see you found out why the pcap file wouldn't open. Sorry for missing the final bits of the pull request, but thanks so much for the fast responses and finishing up the PR!

It was a simple fix of converting the file format from `pcapng` to `pcap`
