### ISSUE TITLE
The callback function tcpReassemblyConnectionEndCallback not be called in sample TcpReassembly

### ISSUE THREAD

**Issue by kdtiankong** [seladb/PcapPlusPlus#419]
The callback function tcpReassemblyConnectionEndCallback not be called in sample TcpReassembly,is this a bug?

I run it by command:
     TcpReassembly  -i ens160 -e "tcp and src port 443", it test the tcp reassemble

**Comment by seladb** [comment]
it should be called whenever a TCP connection is closed by "fin" or "rst" packet.

Do you have a pcap file you can share that shows it's not being invoked?

**Comment by kdtiankong** [comment]
I test it online,interface name is ens160, callback function startconnection and readymsgconnection is called but tcpReassemblyConnectionEndCallback ;
In same environment，I use libnids to test,which  is ok, fin/rst packet is captured and tcp finished ok;

I add some log in tcpReassemblyConnectionEndCallback function, but log not printed;

**Comment by seladb** [comment]
I'm not sure why `tcpReassemblyConnectionEndCallback` that isn't getting called. Here is the place in the code where it should be invoked:

https://github.com/seladb/PcapPlusPlus/blob/7fc447bc4a217d76f7db98c268832bf6ac2e9c8f/Packet%2B%2B/src/TcpReassembly.cpp#L713

As you can see, this code is inside `closeConnectionInternal()` which is invoked in `handleFinOrRst()`:

https://github.com/seladb/PcapPlusPlus/blob/7fc447bc4a217d76f7db98c268832bf6ac2e9c8f/Packet%2B%2B/src/TcpReassembly.cpp#L492

In order to further debug I need a reproducible scenario, like a pcap file or something I can run on my machine. Or you can debug the TcpReassembly code yourself and try to get to the bottom of this.

**Comment by kdtiankong** [comment]
You can input shell command : wget https://github.com/dropbox/json11/blob/master/json11.hpp，
Start tcpreassemble :TcpReassembly  -i ens160 -e "tcp and src port 443"

When debug the TcpReassemble,when the tcp connection is closed ,
the TcpReassembly.cpp:508 is invoked,but closeConnectionInternal is not invoked .so callback function will be not called.

TcpReassembly.cpp:504  argument sideIndex is 0,

**Comment by seladb** [comment]
I think I found the issue: you're using the filter `tcp and src port 443`. This filters all packets sent from the client to the server.

The filter you should be using is: `tcp and port 443`. I tried that and saw that `tcpReassemblyConnectionEndCallback` is getting invoked

**Comment by seladb** [comment]
I'll close this issue now, please reopen it if needed
