### ISSUE TITLE
flowKey of TcpReassembly should be uint64

### ISSUE THREAD

**Issue by DinoStray** [seladb/PcapPlusPlus#447]
According to birthday paradox: [https://en.wikipedia.org/wiki/Birthday_problem](url)  
If we use uint32 for flowKey, when there is 10k tcp connections, it's 75% probability at least one hash collision.  
Now I develop a software will listen 100k tcp connections depend on pcapplusplus, uint32 flowKey  always trigger hash collision.

**Comment by DinoStray** [comment]
![image](https://user-images.githubusercontent.com/6963679/83741986-6d249380-a68b-11ea-9610-bdaae1ba7799.png)

**Comment by seladb** [comment]
while I agree with you, there is a trade off between capacity and the number of collision. I think the question should be: how many collisions do we expect with 100k TCP connections rather than: what is the probability that one (or few) collisions will happen.

with uint32_t we have 2^31 buckets which should be sufficient for 10k or 100k connection with a reasonable number of collisions.

Please let me know what you think

**Comment by DinoStray** [comment]
I think uint64 will make the collisions tolerable.  
And If I do not wanna any collision, what should I do?

**Comment by seladb** [comment]
no collision at all is probably hard to achieve even with uint64.

can you please elaborate on your requirement? why do you need no collision and what collision percentage would be tolerable for you?

**Comment by DinoStray** [comment]
I need monitor every tcp connection, and analyze the data, then report the result.  
Most of the tcp connection used for bitcoin mining.  
If flowKey be uint64, according to birthday paradox, when there is 100k tcp connections, it's 10^-6 probability at least one hash collision. 
It's tolerable for me.

**Comment by DinoStray** [comment]
If we use uint32 for flowKey,  according to birthday paradox,  when there is 10k tcp connections, it's 75% probability at least one hash collision.
I think it's a little intolerable for most situation.

**Comment by seladb** [comment]
I'm still not convinced why one or few collisions for 10k tcp connections (which is 0.01%) should be an issue.

But if you insist on getting to zero collisions you can create you own fork of PcapPlusPlus and change it to uint64. I can help with that if needed

**Comment by DinoStray** [comment]
> I'm still not convinced why one or few collisions for 10k tcp connections (which is 0.01%) should be an issue.
> 
> But if you insist on getting to zero collisions you can create you own fork of PcapPlusPlus and change it to uint64. I can help with that if needed

Now I use the network monitor hashrate of bitcoin, it's about money, I need as as accurately as possible.

**Comment by seladb** [comment]
Ok now I get it. Maybe we need to build a collision detection/prevention mechanism so if 2 different flows have the same flow key we can still distinguish between them. Please let me know what you think

**Comment by DinoStray** [comment]
Now I submit a PR, maybe it's one way to solve the problem.  
I just change flow key to uint64

**Comment by seladb** [comment]
I'm not convinced we should change the key to uint64 because collisions may still occur, depends of the hash function we use. Instead we can add a collision detection/prevention mechanism. 

For example: if a SYN packet matches an existing flow, which means high chances to a collision, we can check whether the IPs and ports match the flow currently on the bucket. If they doesn't we can create a new `TcpReassemblyData` object and chain it on the same bucket

**Comment by seladb** [comment]
I'm closing this issue now, please reopen it if needed
