### ISSUE TITLE
Looking for support for user-defined link layer types 147-162

### ISSUE THREAD

**Issue by l-henken** [seladb/PcapPlusPlus#477]
The current LINKTYPE enumeration does not allow for custom link layer types that many implementations require and tcpdump explicitly provides https://www.tcpdump.org/linktypes.html. Is there a way to write to a pcapng file using link type #147 for example?

**Comment by seladb** [comment]
It's pretty easy to add values to the [`LinkLayerType`](https://github.com/seladb/PcapPlusPlus/blob/2799c51d0692423392c4fc9224e55a9b930845d5/Packet%2B%2B/header/RawPacket.h#L25) enum, however please keep in mind that in order to parse packets correctly PcapPlusPlus needs to know which first layer to expect for each link type. Please refer to the code that does this:

https://github.com/seladb/PcapPlusPlus/blob/2799c51d0692423392c4fc9224e55a9b930845d5/Packet%2B%2B/src/Packet.cpp#L679

As you can see Ethernet (`EthLayer`) is the default layer. If it works for your use-case than all we need to do is to add the values to the enum.

**Comment by l-henken** [comment]
The use-case is writing pcapng files for a proprietary protocol to be then dissected in Wireshark. All that requires is defining the ID block with LinkType 147 ... 162. I was able to achieve this functionality by casting constant 147 to enum LinkType, but it seems very hacky.

**Comment by seladb** [comment]
So what do you suggest? Should we add those values to the enum?

Of course it will work for writing only.

**Comment by l-henken** [comment]
For my use case it would be easy enough to just add these to the enum, but I am unaware of some of the read-side consequences that my use case would not realize. We could just offer these enums for write-side and still short to default on read-side as we currently do. The alternative would be to try and support a new Layer entirely, which I am unfamiliar with but will look into.

**Comment by seladb** [comment]
I tend to agree with your approach.

Would you consider adding these values to the enum?

**Comment by l-henken** [comment]
Yes I can look into it today/

**Comment by seladb** [comment]
your PR was merged to `master`. Thank you so much for your contribution, very much appreciated!
