### ISSUE TITLE
 CPU 100% problem when idle for PfRingDevice::captureThreadMain  function

### ISSUE THREAD

**Issue by jos666** [seladb/PcapPlusPlus#489]
When the thread has data, the cpu low, so how can I determine whether the current CPU usage is problematic or not. Whether the thread is currently in a bottleneck state,

**Comment by seladb** [comment]
As I mentioned in PR #487 CPU is not a good way to determine the load in high volume application because it always stays at 100%.

A better way is to measure the processed vs dropped packets. When a thread is overloaded it cannot handle all packets hence you see a larger number of dropped packets. In `PfRingDevice` you can use `PfRingDevice::getStatistics()`, `PfRingDevice::getThreadStatistics()`, or `PfRingDevice::getCurrentThreadStatistics()` to get stats per thread or for the entire device and measure a rise in the number of dropped packets.

**Comment by jos666** [comment]
Thank you

**Comment by DinoStray** [comment]
what's the meaning of  "high volume application"?
A lot of IO?

**Comment by seladb** [comment]
yes, high volume of incoming/outgoing network traffic
