### ISSUE TITLE
can not parse ppp protocol

### ISSUE THREAD

**Issue by bug65536** [seladb/PcapPlusPlus#493]
hi, pcpp can not parse ppp packet correctly when the head data is `ff 03 00 21`,

![4](https://user-images.githubusercontent.com/42331498/86897349-d9d2f800-c139-11ea-8ed8-e9ea504253a3.png)

![5](https://user-images.githubusercontent.com/42331498/86897360-dd667f00-c139-11ea-873b-4a617f8227ea.png)

this is my issue and pcap data.
[issue.zip](https://github.com/seladb/PcapPlusPlus/files/4889518/issue.zip)

**Comment by seladb** [comment]
apparently there is a special treatment for `ff 03` in Wireshark, which treats these packets as PPP instead of NULL/Loopback:

https://github.com/wireshark/wireshark/blob/master/epan/dissectors/packet-null.c#L117-L142

Adding support for that will be a little tricky because there is no standalone PPP layer in PcapPlusPlus. The existing PPP layer is  associated with GREv1:
https://github.com/seladb/PcapPlusPlus/blob/4ad0476611de1024a94ccced348499f4a74c798d/Packet%2B%2B/header/GreLayer.h#L371

How critical is this for you?
If you want you can make the necessary changes to generalize the existing `PPP_PPTPLayer` and make it fit both use-cases.

**Comment by bug65536** [comment]
thank you very much. I know little about net data protocol. :-)
