### ISSUE TITLE
how to edit http response packet body?

### ISSUE THREAD

**Issue by p1ne4pple** [seladb/PcapPlusPlus#518]
how to edit http response packet body or any raw data api?

**Comment by seladb** [comment]
currently there is no specific API for editing HTTP request/response body. This is because in many cases the data in the message body is compressed and spreads over more than one packet. PcapPlusPlus currently doesn't support gzip decompression and also the only way to get a whole HTTP message (that spreads over multiple packets) is using [TCP reassembly](https://pcapplusplus.github.io/docs/features#packet-reassembly).

Can you further explain your use-case?

**Comment by p1ne4pple** [comment]
hello, glad from you reply.
I am writing a HTTP MITM sample, I want Intercept all response  and then edit or add some content.
I think it can open raw HTTP packet pointer, Let users process abot gzip decompression and other related issues.

**Comment by p1ne4pple** [comment]
In my demonstration, I did not receive any gzip compression data.
So I think this maybe a good idea :)

**Comment by seladb** [comment]
like I mentioned, in many cases an HTTP response contains more than 1 packet so your application needs to: 
1. arrange the packets in the right order
2. extract the TCP payload from each packet
3. glue everything together
4. do gzip decompression, etc.

TCP reassembly can take care of steps 1-3, so you can focus mainly on step 4

**Comment by seladb** [comment]
I'm closing this issue now, please reopen if needed
