### ISSUE TITLE
Problem with Source and Destination address in TcpStreamData from tcpReassembly

### ISSUE THREAD

**Issue by MinusPL** [seladb/PcapPlusPlus#537]
TcpStreamData is one of arguments in tcpReassemblyMsgReadyCallback. All data is properly read, sideIndex also is changing properly, but when I access ConnectionData from TcpStreamData source and destination IP remain in same order as with first time receiving data. I'm not sure if I made some mistake configuring it or is it a problem with TcpStreamData that source and destionation IP never change in tcpData. Or maybe these are meant to not change and I should decide which side (source or destination) is used based on sideIndex value from callback?

**Comment by seladb** [comment]
`ConnectionData` isn't meant to be changed when moving between sides of the connection. It's a data structure that provide information about the IP addresses and ports of the current connection. `ConnectionData.srcIP` is typically the IP address of the client (assuming the connection is captured from its start) and `ConnectionData.dstIP` would be the IP address of the server.

The reason they're not called "clientIP" / "serverIP" is because sometimes there is no client and server, and in other cases the connection may not be captured from the start.

Here is where this structure is being created, as you can see that happens on the first packet of a new connection:

https://github.com/seladb/PcapPlusPlus/blob/master/Packet%2B%2B/src/TcpReassembly.cpp#L139-L145

**Comment by MinusPL** [comment]
So I should check that based on sideIndex then. Thank you very much, also to not open new one I'll ask here too. Does TCPReassembly know how to handle duplicates of packets? It seems that I have many duplicates after reassembly. This makes thing much worse to read.

**Comment by seladb** [comment]
Yes, it should ignore any TCP re-transmission which might cause duplicated data: https://github.com/seladb/PcapPlusPlus/blob/master/Packet%2B%2B/src/TcpReassembly.cpp#L305-L342

I'm not sure why you're seeing duplicates, maybe your protocol transmits the data again?

**Comment by MinusPL** [comment]
I'm not aware of any retransmissions in protocol I'm working on, but for now let's just say that it might or might not happen in my case. It's only small problem compared to whole packet being in parts that are not in order.
For now it is safe to close this issue then. If I notice that duplicated packets are still left after reasembly and I have information if protocol I'm working with isn't sending them again on it's own then I might write once again. Thansk for your time. :)

**Comment by seladb** [comment]
thanks @MinusPL ! Please don't hesitate to reach out if you have more questions
