### ISSUE TITLE
centos7 and dpdk 17.02.1 support?

### ISSUE THREAD

**Issue by nmygb** [seladb/PcapPlusPlus#54]
cenots7, gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) ,  dpdk 17.02.1
make all

![20170612113404](https://user-images.githubusercontent.com/8006440/27018436-2588a1a6-4f63-11e7-8145-0c645a23760f.png)

**Comment by nmygb** [comment]
in /root/dpdk-stable-17.02.1/build/include/rte_pci.h：
#include <inttypes.h> 
this does not seem to work, and I do not know why
Finally, I added the definition of PRIx8 and PRIx16 myself，the Compiled through


#ifndef PRIx8
#define PRIx8 "x"
#endif

#ifndef PRIx16 
#define PRIx16 "x"
#endif

/** Formatting string for PCI device identifier: Ex: 0000:00:01.0 */
#define PCI_PRI_FMT "%.4" PRIx16 ":%.2" PRIx8 ":%.2" PRIx8 ".%" PRIx8
#define PCI_PRI_STR_SIZE sizeof("XXXX:XX:XX.X") 
。。。

**Comment by seladb** [comment]
Hi, I googled this problem and found a similar issue: https://github.com/scylladb/seastar/issues/235
Which was solved by adding an include to all relevant DPDK files: `#include <cinttypes>` https://github.com/scylladb/seastar/commit/3b052bd260f36c07c69c0b4789530fbb106b0341
Since I don't have CentOS7, could you please add this include to all DpdkDevice.cpp and DpdkDeviceList.cpp and see if it works? If so, you could issue a pull request or I can do this change and push it to master

**Comment by seladb** [comment]
Eventually the solution was a little bit different - I just needed to add the macro `#define __STDC_FORMAT_MACROS` to `DpdkDevice.cpp` and `DpdkDeviceList.cpp`  and that solved the problem.
I verified it's working on both CentOS 7 and on Ubuntu
