### ISSUE TITLE
TcpReassembly does not work properly

### ISSUE THREAD

**Issue by prujan** [seladb/PcapPlusPlus#554]
TcpReassembly v20.08+ (non-official release)
Built: Dec 21 2020 11:31:01
Built from: Git branch 'master', commit '54fcc6190efeeb54dc6d66c809ec7b7e7308eab8'
i'm running  TcpReassembly -r pcap_examples/tcp-new.pcap -o .
i reordered the GET packet #4 and place #7
[tcp-new.txt](https://github.com/seladb/PcapPlusPlus/files/5730953/tcp-new.txt)

Please change the extension to pcap.
The output
[172.16.133.54.64370-23.21.118.18.80.txt](https://github.com/seladb/PcapPlusPlus/files/5730957/172.16.133.54.64370-23.21.118.18.80.txt)
 is not ordered flow, but exactly as tcp-reassembly

Please assist,

Thank Michael.

**Comment by seladb** [comment]
hi Michael, I looked into the example you attached, and here is what happens:
You moved the first HTTP request packet between the 2 corresponding HTTP response packets. The sequence now is as follows:
```
Packet# | Client->Server  | Server->Client             
--------+-----------------+-----------------------------
1       | SYN (seq=0)     |
2       |                 | SYN/ACK (seq=0)
3       | ACK (seq=1)     |
4       |                 | ACK (seq=1) - ignored
5       |                 | Response Packet#1 (seq=1)
6       | Request (seq=1) |
7       |                 | Response Packet#2 (seq=1461)
``` 

As you can see, from TCP point-of-view this flow makes sense, and that's why you're getting the request data in the middle of the response. TCP reassembly looks only at TCP data, it knows nothing about HTTP or other higher-level protocols.
BTW, I tried using "Follow->TCP stream" in Wireshark and it gives the same result.
Please let me know if that makes sense to you.

**Comment by prujan** [comment]
Hi,
You are completely rigth,
Thanks
