### ISSUE TITLE
Unable to parse DNS layer for TCP traffic

### ISSUE THREAD

**Issue by kevsjh** [seladb/PcapPlusPlus#583]
Hi there, just started using pcap++ for the first time today, very impressed with the overall speed. 
I am reading pcap data and parsing its content, i was not able to parse DNS layer for TCP traffic. No issue for UDP traffic.

The DNS layer is present for TCP traffic when viewed from wireshark

I am trying the following way of parsing

pcpp::DnsLayer *dnsLayer = parsedPacket.getLayerOfType<pcpp::DnsLayer>();
            if (dnsLayer == NULL)
            {
                printf("Something went wrong, couldn't find DNS layer\n");
            }

**Comment by seladb** [comment]
The reason you can't find DNS over TCP is because PcapPlusPlus only supports DNS over UDP.

Here is the code that parses DNS over UDP:
https://github.com/seladb/PcapPlusPlus/blob/master/Packet%2B%2B/src/UdpLayer.cpp#L111-L112

There is no similar code for TCP:
https://github.com/seladb/PcapPlusPlus/blob/d6c46ef809d29a71f84b2d3d8689a2456b51e41a/Packet%2B%2B/src/TcpLayer.cpp#L342

But it's a very easy fix. Assuming DNS ports over TCP are similar to UDP ([here](https://github.com/seladb/PcapPlusPlus/blob/master/Packet%2B%2B/header/DnsLayer.h#L464-L474) are the ports PcapPlusPlus considers as DNS) then all we need to add similar code for TCP layer.

Would you consider making the fix and open a PR?

**Comment by kevsjh** [comment]
Thank you for the suggestion. I've applied the fixes as suggested and was able to parse DNS for TCP packets.

However, i ran into the following error when parsing some  of the TCP packet

_DNS layer contains more than 300 resources, probably a bad packet. Skipping parsing DNS resources_

Increasing the resource level further resulted in the following error

_DNS parsing error: name pointer is illegal_

```
if (numOfOtherResources > 40000)
	{
		LOG_ERROR("DNS layer contains more than 300 resources, probably a bad packet. "
				"Skipping parsing DNS resources");
		return;
	}
```

[sometcpdns.zip](https://github.com/seladb/PcapPlusPlus/files/5927408/sometcpdns.zip)
attached the tcp dns pcap sample for reference

**Comment by kevsjh** [comment]
also, with TCP dns parsing, wasn't able to get the dns query name, but was able to get the type and transaction id

```
pcpp::DnsQuery *dnsquery = dnsLayer->getFirstQuery();
std::cout << "dnsquery name " << dnsquery->getName() << std::endl;
std::cout << "type " << dnsquery->getSize() << std::endl;
std::cout << "transaction id " << dnsLayer->getDnsHeader()->transactionID << std::endl;
```
example of output for 1 packet:
```
dnsquery name
type 5
transaction id 9984
```

**Comment by seladb** [comment]
@kevsjh I found the issue!
Apparently DNS over TCP has one additional field: `length` which isn't there in DNS over UDP. It's also [mentioned in the RFC](https://tools.ietf.org/html/rfc7766#section-8). I think the reason for that field is that DNS over TCP can spread over more than one packet so `length` indicates the total size of the message.

Unfortunately this is not currently supported in PcapPlusPlus. We need to think how to implement it in a way that will support all the current functionality. If you have any ideas please feel free to suggest or open a PR and we can discuss.

![image](https://user-images.githubusercontent.com/9059541/107010400-25d73100-674b-11eb-9748-09dca405b8c4.png)

**Comment by kevsjh** [comment]
Hi @seladb 
Yes you are correct. 
It seemed that DNS over TCP was introduced in RFC 7766 back in 2016 March. It's rather new, and I tried libtins as well as Google's goPacket. Both do not support DNS over TCP.

However, I was able to get it working on libtins with my below function. Based on RFC7766, the only diff between DNS over UDP and TCP is the 2byte length field in it. Once omitted, the payload will be accepted as DNS.

If you don't mind, I'll be willing to help add this to pcap++ as well. Do you mind pointing me to where I can get the tcp payload and the func to modify it?

> Below is the function i used on libtins

`
 //retrieve TCP layer PDU payload
            RawPDU *raw = tcp->find_pdu<RawPDU>();
            // check if there's payload layer after TCP
            if (raw != nullptr)
            {
                // check if payload size is larger than  2, parse TCP dns if thats the case
                if (raw->payload_size() > 2)
                {
                    
                    RawPDU::payload_type &payload = raw->payload();
                    // Omit the first 2 byte of DNS length field, only included
                    // in TCP based on RFC7766, in order to reuse the DNS UDP parser
                    payload.erase(payload.begin(), payload.begin() + 2);
                    //parse the modified payload to DNS parser
                    DNS dns = raw->rfind_pdu<RawPDU>().to<DNS>();
                    std::cout <<dns.id() << std::endl;

`

**Comment by seladb** [comment]
Thanks @kevsjh for your offer to help, I'd really appreciate your contribution!

Regarding the libtins change you posted - I'm not sure the right solution should be removing those 2 bytes. I think we should come up with a solution that will keep these bytes and still provide all the functionality of DNS over UDP.

Perhaps we can do something like this:

**Step 1:** add a flag to all of the [constructors of `DnsLayer`](https://github.com/seladb/PcapPlusPlus/blob/master/Packet++/header/DnsLayer.h) indicating whether it's DNS over TCP or DNS over UDP. The default should be UDP. We can keep this flag as a private member of `DnsLayer`

**Step 2:** make several changes depending on the flag's value:
- Packet parsing:
  - The [`getDnsHeader()`](https://github.com/seladb/PcapPlusPlus/blob/b02af27b6170b81888d4554da2a8a4c871e6f094/Packet%2B%2B/header/DnsLayer.h#L136) should take this flag into account and return the correct offset
  - In [`parseResources()`](https://github.com/seladb/PcapPlusPlus/blob/b02af27b6170b81888d4554da2a8a4c871e6f094/Packet%2B%2B/src/DnsLayer.cpp#L126) the value of `offsetInPacket` should be determined by this flag
  - We should add a method `getTcpMessageLength()` that will return the length value if this is DNS over TCP (and probably 0 and error log if it's DNS over UDP)
- Packet crafting / editing:
  - The [`DnsLayer()` constructor](https://github.com/seladb/PcapPlusPlus/blob/b02af27b6170b81888d4554da2a8a4c871e6f094/Packet%2B%2B/src/DnsLayer.cpp#L31) and [copy constructor](https://github.com/seladb/PcapPlusPlus/blob/b02af27b6170b81888d4554da2a8a4c871e6f094/Packet%2B%2B/src/DnsLayer.cpp#L45) should create the raw data according to this flag
  - In [`addResource()`](https://github.com/seladb/PcapPlusPlus/blob/b02af27b6170b81888d4554da2a8a4c871e6f094/Packet%2B%2B/src/DnsLayer.cpp#L481) the initial offset should be adjusted
  - In [`addQuery()`](https://github.com/seladb/PcapPlusPlus/blob/b02af27b6170b81888d4554da2a8a4c871e6f094/Packet%2B%2B/src/DnsLayer.cpp#L557) the initial offset should be adjusted

**Step 3:** add the code in [`TcpLayer`](https://github.com/seladb/PcapPlusPlus/blob/b02af27b6170b81888d4554da2a8a4c871e6f094/Packet%2B%2B/src/TcpLayer.cpp#L342) to parse DNS packets and create an instance of `DnsLayer` with flag = `true`

**Step 4:** add [unit-tests to `DnsTests.cpp`](https://github.com/seladb/PcapPlusPlus/blob/master/Tests/Packet++Test/Tests/DnsTests.cpp). We can probably use the packets you attached as examples

I hope I'm not missing anything... please let me know what you think.

**Comment by seladb** [comment]
I have some good news, I've added DNS over TCP support! It is now merged to `master` so you can pull the latest commit and use it.

I ended up implementing a slightly different solution: I've added a new class (layer) called [`DnsOverTcpLayer`](https://github.com/seladb/PcapPlusPlus/blob/091dd8ce1d76af950572a46952e65bd99b5b7eff/Packet%2B%2B/header/DnsLayer.h#L491) which inherits `DnsLayer` and adds the 2-byte offset needed for parsing, editing and creation of DNS over TCP messages.
Since `DnsOverTcpLayer` inherits from `DnsLayer` you can treat these messages as `DnsLayer` objects and use all the methods it exposes. The only methods which are explicit to `DnsOverTcpLayer` are a getter and setter for "TCP message length" which is only available in DNS over TCP messages. 
If you want to learn more about how to use it you can take a look at the unit-tests:

Parsing DNS over TCP:
https://github.com/seladb/PcapPlusPlus/blob/091dd8ce1d76af950572a46952e65bd99b5b7eff/Tests/Packet%2B%2BTest/Tests/DnsTests.cpp#L635

Edit/create DNS over TCP:
https://github.com/seladb/PcapPlusPlus/blob/091dd8ce1d76af950572a46952e65bd99b5b7eff/Tests/Packet%2B%2BTest/Tests/DnsTests.cpp#L728

Please let me know if you have any questions or comments.
I'll close this issue now, please reopen if needed.

**Comment by Michael0415** [comment]
Hi, I compiled a latest source code , and when I captured packets with the async capture, and It still prompt like this, 
![image](https://user-images.githubusercontent.com/18414020/156696794-0358feb0-c4f0-4b4c-ba71-c43dd2f4762c.png)
