### ISSUE TITLE
reallocate mBuf Error in DPDK Bridge

### ISSUE THREAD

**Issue by mohammadMighani** [seladb/PcapPlusPlus#590]
hi am using pcap++ and Dpdk (19.11) and in the DpdkBridge example sometimes (i dont know exactly when)a got this error:

_Cannot reallocate mBuf raw packet to a size larger than mBuf data. mBuf max length: 2048; requested length: 3028_
in  DpdkDevice::receivePackets(pcap::MBufRawPacket** , unsigned short, unsigned short)
in appWorkerThread::run(unsigned int) ()

i use main branch on this commit:
_commit ea577d9cda23608671edfaef705eabc33de97273
Author: seladb <pcapplusplus@gmail.com>
Date:   Tue Dec 22 00:32:15 2020 -0800
Fix typo_

Tell me if you need more information.

**Comment by seladb** [comment]
I think this is because the size of the packet is more than 2048 bytes which is the default size of a DPDK mbuf. For larger packets than the solution should be allocating more mbufs and chaining them together, however this is currently not supported in PcapPlusPlus. A way around could be, if you know the max packet size in your network, to change the default mbuf size which is determined in [`MBUF_DATA_SIZE`](https://github.com/seladb/PcapPlusPlus/blob/3b8c9ef5fbab28cc406b4e6b894be0c6e7118cd4/Pcap%2B%2B/header/MBufRawPacket.h#L47). I haven't tried it though so I'm not sure if DPDK will allow an mbuf which is larger than 2048 bytes...

**Comment by seladb** [comment]
I'll close the issue now, please reopen if relevant
