### ISSUE TITLE
PortFilter SRC_OR_DST does not work properly in combi with AndFilter

### ISSUE THREAD

**Issue by whati001** [seladb/PcapPlusPlus#591]
Hi guess, first of all thx for the nice work, but to me it seems that the direction SRC_OR_DST does not work properly for PortFilter in combination with AndFilter.

Maybe my code is wrong, so please checkout the filter creation snipped below:
```c++
void rehka::SipSniffer::prepareSipFilter() {
    pcpp::AndFilter filter;

    pcpp::PortFilter portFilter = pcpp::PortFilter(6050, pcpp::SRC_OR_DST);
    filter.addFilter(&portFilter);

    pcpp::ProtoFilter protocolFilter(pcpp::UDP);
    filter.addFilter(&protocolFilter);

    std::string strFilter;
    filter.parseToString(strFilter);
    std::cout << "Finished preparing Sip Filter: " << strFilter << std::endl;
    // sipFilter -> class member
    sipFilter_ = strFilter;
}
```
The code generates following filter: `(src or dst port 6050) and (udp)`.
If we apply this filter to the PcapReader, all packages get filtered out.
But there are packages included which should pop up.

I have received the desire output by applying following filter `(src port 6050 or dst port 6050) and (udp)`.

Running ArchLinux x86-64 with kernel version 5.10.16-arch1-1

**Comment by whati001** [comment]
Please see a fixed version on my fork [here:](https://github.com/whati001/PcapPlusPlus/tree/Issue591-PortFilter)
![image](https://user-images.githubusercontent.com/16085873/108635958-9936ad80-7482-11eb-97f0-dc7dc16bea45.png)

I have started today with your lib, so all those filters are a little bit new to me. But it's quite unreasonable that we store the string instead of the uint_16 value. This makes it a little bit complicated to build complex Filters with the help of the simple ones, due to the require an integer.

**Comment by seladb** [comment]
thanks @whati001 for reporting this issue. Let me check and get back to you

**Comment by whati001** [comment]
have fixed the `PortFilter` in my forked branch like [this](https://github.com/whati001/PcapPlusPlus/blob/cd07cff83a55eed70ee89bdb403ee9b504ecff47/Pcap%2B%2B/src/PcapFilter.cpp#L258).

But it seems to me, that those filters `AndFilter` and `OrFilter` face a memory corruption.
Both maintain a list of filters pointers. Let's consider the case where the user allocates those filters on the heap, we should have a mem leak due to missing dtor. If we allocated them on the stack and go out of scop, a address violation will occur.

![image](https://user-images.githubusercontent.com/16085873/108688223-f751a800-74f7-11eb-8c17-a48db6441ed4.png)

Only valid use would be to allocate in the stack, add to `{Or,And}Filter` and generate the string reputation right away without storing the Filter instance itself.

**Comment by seladb** [comment]
hi @whati001 , I looked into this and I can't reproduce your issue. The syntax of `src or dst port XXX` should be valid according to [the documentation](https://biot.com/capstats/bpf.html) and it does work on my machine. I tried to run [`PcapPrinter`](https://github.com/seladb/PcapPlusPlus/tree/master/Examples/PcapPrinter) with both DNS and SIP pcap files with a similar syntax:
`(src or dst port 53) and (udp)`
`(src or dst port 5060) and (udp)`

Both work and produce the expected output.

In the example you used port 6050 instead of 5060, maybe this is the issue?

And regarding the memory corruption you mentioned, this is a common problem in C++ - you need to know where objects are allocated. If objects are freed or go out of scope, other objects that point to them will face a memory corruption. I don't think it's a unique issue of this code. A possible alternative implementation could be to copy the inner filters and store them inside the AND/OR filters instead of keeping just the pointers, but I think the current solution is a little bit cleaner and requires less data copying.
Please let me know what you think.

**Comment by whati001** [comment]
hi @seladb sorry for the BPF filter syntax issue. Seems like I have messed up something somewhere. Everything works perfectly. Your assumption with overlooking the port must be right.

Regarding the filter reference. For sure, the developer is in charge to maintain the mem properly. But it just looks a little bit odd to me, to consume pointers without defining a dtor. So I would just add a dtor and make the ctor for PortFilter private to avoid allocation on stack. In addition, we could support proper creation via static methods, which do all the magic.

**Comment by seladb** [comment]
Thanks for the update @whati001 !

I'm not sure I'm following you regarding the filters redesign:

> So I would just add a dtor and make the ctor for PortFilter private to avoid allocation on stack

How would you create a standalone `PortFilter` instance if the c'tor is hidden (assuming you want just a port filter, not as part of an AND/OR filter)?

> In addition, we could support proper creation via static methods, which do all the magic

I'm not sure I understand how static methods can solve this issue. Can you provide some code or pseudo-code to explain your idea?

**Comment by whati001** [comment]
What make this thing a little bit weird to me is, that for example the `AndFilter` consumes the `PortFilter`, but the developer needs to guarantee that the `PortFilter` mem does not get invalid. Sorry I do not have the project any more open, but this should fail due to out of scope error:
```c++
class A {
  private:
    pcpp::AndFilter andFilter_;

  puplic:
    A();
}

A:A() {
  // create a more complex filter with the basic ones
  pcpp::PortFilter portFilter = pcpp::PortFilter(2711);

  // store the complex one as memeber for later usage
  andFilter_.addFilter(&portFilter);
}
```
And because we use normally the basic blocks to build the advanced one, this scenario can occur with a high potential.
Let's consider the case we allocated the `PortFilter` on the heap -> which is somehow signed by the fact that we have to pass a pointer. I would then allocate the basic filters on the heap, add them to the complex one and **only** store the complex one. This one should have the reference to all the basic ones. But due to missing dtor, we have also to remember the basic ones.
Because we need to delete them after the complex got deleted. 


Not sure if this assumption is wrong, but to me, a memory leak (especially for those filters where only on top 10 - 20 instances will exists) is more tolerable than a pointer into the memory. By making the ctor private, nobody can allocate them on the stack. 
For creation, we can use a static function inside the class or a Factory Pattern:
```c++
// Factory to create new Filter only on the Heap
class PortFactory {
  public:
    static createPortFilter(uint16_t port) {
       return new PortFilter(port);
  }
}

class PortFilter : public IFilterWithDirection
{
  private:
  std::string m_Port;
  void portToString(uint16_t portAsInt);
  
public:
  static newPortFilter(uint16_t port) {
    return new PortFilter(port);
  }
...
```
And a dtor for the complex filters which call `delete` to each element in there vector.

Or to avoid all this stuff, just pass them by value. But guess you do not want to pass as value due to speed concerns?
It seems like every Filter is derived from the `GeneralFilter`, which owns a `bfp_wrapper`. Just a brainf*, what if we change the logic in a way, that the PortFilter just holds the BPF expression as string and no `bfp_wrapper`? In this case a copy would be quite fast I guess.

**Comment by seladb** [comment]
I think I get your point @whati001 . You're right that if you create an instance of a complex filter you expect it to manage its own memory and not expect the user to keep the sub-filters that were given in the c'tor alive. The easiest and most intuitive solution in my opinion would be to pass the filters by value in the c'tor and keep a copy of them in the complex filter. I'm not very worried about memory consumption or speed because filter creation is usually done outside of the data path and you don't expect a large number of these objects to exist simultaneously in an app.
I think the required change is quite small and should apply to all of the complex filters: `AndFilter`, `OrFilter` and `NotFilter`. We can probably ignore a proper coping the `bpf_program` object because it's only used to match a packet against a filter so if you give a filter in the c'tor to a complex filter it shouldn't mean anything.

Would you consider making this change and open a PR?

**Comment by whati001** [comment]
Sure I will go for it, but need some time, a little bit blocked right now with other stuff.

**Comment by seladb** [comment]
> Sure I will go for it, but need some time, a little bit blocked right now with other stuff.

Sure no worries, please take your time. Let me know if you need any help

**Comment by seladb** [comment]
thanks @whati001 for working on this!
The changes look good to me. Once you fix the tests please open a PR and I'll review it. Thanks again!

**Comment by seladb** [comment]
hi @whati001 , did you have a chance to work on this lately? Please let me know if there's anything I can do to help

**Comment by whati001** [comment]
sorry for the late reply, will try to tackle it this week

**Comment by whati001** [comment]
Let's keep things how they are. Sorry for this feedback, but by passing the simple filters via value, we are not able to use the c++ polymorphism. Hence filter expression generation will break for the complex one.
