### ISSUE TITLE
[bug] wrong length of tcp option [ pcpp::PCPP_TCPOPT_WINDOW ]

### ISSUE THREAD

**Issue by bug65536** [seladb/PcapPlusPlus#592]
hi, I modified the example code PcapPlusPlus/Examples/Tutorials/Tutorial-PacketCraftAndEdit/main.cpp

by  adding code :

`
// add MSS TCP option
tcpLayer->addTcpOptionAfter(pcpp::TcpOptionBuilder(pcpp::TCPOPT_MSS, (uint16_t)1460));

**tcpLayer->addTcpOptionAfter(pcpp::TcpOptionBuilder(pcpp::PCPP_TCPOPT_WINDOW, (uint16_t)1));**
`
and then run the example, i opened 1_modified_packet.pcap.cap with wireshark, and it tell me it was wrong, because the length of this option is 3, not 4.

![2021-02-23 17-32-12 创建的截图](https://user-images.githubusercontent.com/42331498/108824849-2ef64800-75fd-11eb-8b00-73aeec13b47d.png)

**Comment by bug65536** [comment]
maybe it should be 0x03 03 01, not 0x03 04 00 01 ?  :-)

**Comment by seladb** [comment]
hi @bug65536 , I found the issue: the TCP window scale option has a length of 3 bytes, which means its data has a size of 1 byte.
This means you should add it like this:
```cpp
tcpLayer->addTcpOptionAfter(pcpp::TcpOptionBuilder(pcpp::PCPP_TCPOPT_WINDOW, (uint8_t)1));
```
If you cast the value to `uint8_t` instead of `uint16_t` PcapPlusPlus will create a TCP option with a size of 3 bytes which is exactly what you need:

![image](https://user-images.githubusercontent.com/9059541/108961519-51ec2080-762c-11eb-800a-2b5be47e787f.png)

Please let me know if you have any questions.

**Comment by bug65536** [comment]
thank you very much for your great job! :-)
