### ISSUE TITLE
Building for Apple Silicon (MacOS, ARM64)

### ISSUE THREAD

**Issue by szigetics** [seladb/PcapPlusPlus#596]
I would like to build the library for Apple Silicon (MacOS, ARM64).
  
How could I achieve that?

**Comment by seladb** [comment]
That's a good question! I haven't tried building it for Apple Silicon (M1) but I don't think there should be a problem.
It looks like libpcap is already available for Apple Silicon: https://formulae.brew.sh/formula/libpcap
So assuming you have it installed on your M1 machine you can probably follow the same process as any macOS machine: https://pcapplusplus.github.io/docs/install/build-source/macos
Please let me know if you see any issues.

Unfortunately I cannot add M1 to PcapPlusPlus CI because M1 machines are not yet available on [GitHub Actions](https://github.com/actions/virtual-environments/issues/2187), and I don't think they're available in TravisCI and CirrusCI as well.

**Comment by szigetics** [comment]
> It looks like libpcap is already available for Apple Silicon: https://formulae.brew.sh/formula/libpcap

@seladb  : Thank you for your quick response! 👍 

brew says its pcapplusplus package is already available for Apple Silicon : https://formulae.brew.sh/formula/pcapplusplus .
So I believe that they say that they support Apple Silicon even if it is running only via rosetta...

**Comment by seladb** [comment]
Thanks @szigetics  I didn't even know PcapPlusPlus is already available for Apple Silicon 🤣 
homebrew is probably compiling all their libraries again Apple Silicon... I'm not sure if they're using rosetta or not.
Please let me know if you see any issues.

**Comment by szigetics** [comment]
@seladb  : 
I checked on an ARM64 machine : it turned out that the brew binary was indeed built for arm64 : 
<img width="434" alt="Screenshot 2021-03-05 at 16 40 02" src="https://user-images.githubusercontent.com/7099208/110137700-72a53a80-7dd1-11eb-9dd8-76c67b122767.png">

so I take on this task, and I have something that works, and cross-compiles for arm64 from an x86_64 machine : https://github.com/szigetics/PcapPlusPlus/compare/v20.08...szigetics:v20.08_macos_arm64_cross_compilation_support-2?expand=1 .

```
% cd Dist
% find ./ -name "*.a" -exec lipo -info {} \;
Non-fat file: .//libPcap++.a is architecture: arm64
Non-fat file: .//libCommon++.a is architecture: arm64
Non-fat file: .//libPacket++.a is architecture: arm64
```

I will open a PR to your repo once I cleaned this up properly.

**Comment by seladb** [comment]
Thank you so much for investing your time and efforts in this!
I'll be looking forward for your PR!

I look at the current code and have a few suggestions:
- Since we're basically adding build flags you can consider adding a `PcapPlusPlus.macosx.arm64` in the [`mk/`](https://github.com/seladb/PcapPlusPlus/tree/master/mk) directory and copy its content to the `PcapPlusPlus.mk` file in the same way [we do on Linux](https://github.com/seladb/PcapPlusPlus/blob/091dd8ce1d76af950572a46952e65bd99b5b7eff/configure-linux.sh#L292)
- We can also change [LightPcapNg Makefile](https://github.com/seladb/PcapPlusPlus/blob/master/3rdParty/LightPcapNg/Makefile) to accept the flags that are needed by setting a flag in `platform.mk` or `PcapPlusPlus.mk`

**Comment by seladb** [comment]
hi @szigetics , do you have any updates on this?

**Comment by szigetics** [comment]
Hi! @seladb : Thank you for your suggestions! No, I don't have any update yet. I got this on my TODO list. Eventually I will get there : probably this week.

**Comment by szigetics** [comment]
@seladb : I just opened a PR for this : https://github.com/seladb/PcapPlusPlus/pull/607 .

**Comment by seladb** [comment]
Thank @szigetics, I really appreciate your efforts! Please give me a day or two to review the PR

**Comment by szigetics** [comment]
@seladb : Now that the relevant PR is merged : https://github.com/seladb/PcapPlusPlus/pull/607 , this issue could be closed.
