### ISSUE TITLE
Is there a unified encapsulated packet receiving and sending function?  

### ISSUE THREAD

**Issue by angelyouyou** [seladb/PcapPlusPlus#610]
Is there a unified encapsulated packet receiving and sending function?  These functions are used to shield the differences of different packet sending and receiving technologies?  Can the user switch easily and conveniently?

**Comment by seladb** [comment]
I'm not sure I'm following you. Can you please explain what you mean by encapsulated function?
There are different methods under `PcapLiveDevice` for receiving and sending packets, what do you think is missing?

**Comment by angelyouyou** [comment]
@seladb 
What I mean is that different receiving and sending packet models can be encapsulated into a unified set of entry functions, so that users can more easily switch between these different technologies without too much awareness of these underlying function interfaces or implementations. Differences in principle.
For example, the current programming is:
1. If DPDK technology is used to send and receive packets, DPDK_XXX_Recv/DPDK_XXX_Send will be used;
2. If PF_RING technology is used, use PF_RING_Recv/PF_RING_Send
.....
Can we provide a unified programming interface? For example, socket supports sending and receiving of different types of data packets, but the functions exposed to the outside are all socket/recv/send/sysctl. That is, an adaptation layer is added to shield and abstract the differences of different technologies as much as possible.

**Comment by seladb** [comment]
Thanks for sharing your thoughts @angelyouyou !
The interface for receiving and sending packets is pretty similar between the different technologies.
Each technology has each own class, for example: 
1. [`PcapLiveDevice`](https://pcapplusplus.github.io/api-docs/classpcpp_1_1_pcap_live_device.html) for libpcap
2. [`WinPcapLiveDevice`](https://pcapplusplus.github.io/api-docs/classpcpp_1_1_win_pcap_live_device.html) for WinPcap/Npcap
3. [`DpdkDevice`](https://pcapplusplus.github.io/api-docs/classpcpp_1_1_dpdk_device.html) for DPDK
4. [`PfRingDevice`](https://pcapplusplus.github.io/api-docs/classpcpp_1_1_pf_ring_device.html) for PF_RING
5. [`RawSockerDevice`](https://pcapplusplus.github.io/api-docs/classpcpp_1_1_raw_socket_device.html) for raw sockets

You can see the full device tree here: https://pcapplusplus.github.io/api-docs/classpcpp_1_1_i_device.html (all of them inherit from `IDevice`)

All of them have send an receive methods, although their signature might slightly change because of the implementation details of each technology. In the end, the purpose of PcapPlusPlus is to create a simple yet powerful API for all of these technologies, in a way that is easy to use and expose as much of the functionality and strength each technology offers.

Please let me know if it makes sense.

**Comment by angelyouyou** [comment]
@seladb thanks a lot.
I want to relplay some packets with dip will be modified.How can I send the packets without knowing the MAC address of the dip.

**Comment by seladb** [comment]
I'm not sure what dip is... but generally speaking you need to know the MAC address in order to send packets and be sure they arrive to their destenation

**Comment by seladb** [comment]
I'll close this issue for now, please reopen if relevant
