### ISSUE TITLE
Get HTTP Message Body

### ISSUE THREAD

**Issue by LeukocytesTT** [seladb/PcapPlusPlus#648]
How can I get the http message body? I only can find that the first line could be parsed!

**Comment by seladb** [comment]
hi @LeukocytesTT , PcapPlusPlus does not currently parse the HTTP message body. The reason is that in most cases the HTTP body spreads over more than one packet, and PcapPlusPlus focuses on parsing single packets. Parsing the body will require [TCP reassembly](https://pcapplusplus.github.io/docs/features#packet-reassembly) first (if packets are out of order), then stitch the packets together and eventually parse the data (for example: unzip gzipped data, etc.). All of this doesn't currently exist in PcapPlusPlus. It is there in my long-term roadmap but I'm not sure when I'll get to it.

**Comment by seladb** [comment]
@LeukocytesTT I'll close this issue now, please reopen if needed
