### ISSUE TITLE
TcpReassembly malfunction 

### ISSUE THREAD

**Issue by aemontilla** [seladb/PcapPlusPlus#656]
TcpReassembly malfunction

I have found a malfunction of the reassembly example, with live traffic capture of disorganized packets, the program goes into a loop and never checks for disordered fragments, even when the traffic is normalized

I use version 20.08

I reproduced the problem with the following pcap file
[test.zip](https://github.com/seladb/PcapPlusPlus/files/6542712/test.zip)

Thanks for your attention

**Comment by seladb** [comment]
thank @aemontilla for reporting this issue! Before we go deeper into this issue, can you please test with the latest version v21.05?

**Comment by aemontilla** [comment]
Hello
If I did the test with the new version and the same thing happens, with the pcap file at the end of the reading it frees the fragments, but in a live capture it does not. What are the conditions for me to release the disordered fragments?

**Comment by seladb** [comment]
hi @aemontilla , I looked at the pcap file you shared. I think this pcap has a few issues:
- It only contains data from 192.168.200.6 to 192.168.200.5. It doesn't contains data in the opposite direction
- This pcap file doesn't have the beginning of the flow

Because the beginning of the connection is missing all packets are considered out-of-order, and since there is no data from the opposite side there is no trigger to "release" them. Usually if we see traffic in both sides - once traffic from the other side begins, all out-of-order packets from the other side are released. You can see the comment here for more details: https://github.com/seladb/PcapPlusPlus/blob/master/Packet++/src/TcpReassembly.cpp#L242-L251

What I'd recommend is either to capture data from both sides, or at least capture data from the beginning of the TCP connection (meaning from the SYN packet)

**Comment by aemontilla** [comment]
Hello, thanks
In this scenario, a test of a client-server connection is performed, and one of the sides does not transmit information. In addition, a filter per port is also being applied.
Communication is altered using cloumsy software, a latency simulator, duplicate packets, etc.
From what I understand Pcap ++ Reasembly does not support the scenario where there are disorganized packages and there is no traffic from the other side, is this so?

**Comment by seladb** [comment]
@aemontilla thanks for providing more details about your scenario!
I think I have a solution for this use case: one of the parameters of `TcpReassembly`'s c'tor is `TcpReassemblyConfiguration &config`. This config struct contains a few flags that can control the `TcpReassembly` behavior. One of these parameters is [`maxOutOfOrderFragments`](https://pcapplusplus.github.io/api-docs/structpcpp_1_1_tcp_reassembly_configuration.html#a760cfdaff04fc2c37da820a7a092c989) which can limit the number of out-of-order packets that are stored per connection. I think that you can use this parameter to release the packets after a certain threshold is met. Please let me know if you think this may help.

**Comment by seladb** [comment]
@aemontilla did you have a chance to look at my previous comment? Should we keep this issue open?

**Comment by seladb** [comment]
I'm closing this issue, please reopen if needed
