### ISSUE TITLE
How/Why UDP port changed when parsed new protocol？

### ISSUE THREAD

**Issue by angelyouyou** [seladb/PcapPlusPlus#658]
I am trying to add a new netflow protocol in opensource project. But when I run it I found the UDP port （destination port is 9996, source port is 61985）parsed changed when judge the application.I do not know the reason.Please help me.Thanks very much!

Here is my [project](https://github.com/angelyouyou/PcapPlusPlus) .

I put one .mov file to show the issue.

**Comment by seladb** [comment]
hi @angelyouyou , I've watched the video file and I'm not sure why the UDP port suddenly changed. Maybe it's a glitch in your debugger? I can't find any reason why it should happen...

P.S 
I think it's better if you attach the video to this issue instead of putting it in the repo, so it's easier to track it

**Comment by angelyouyou** [comment]
@seladb 
Thanks for your help.I will try it late.
I attach my video to my project because the file size limit.....
