### ISSUE TITLE
PcapPlusPlus DPDK support for Windows

### ISSUE THREAD

**Issue by HagaiVinik** [seladb/PcapPlusPlus#747]
Hi, I have used PcapPlusPlus running on DPDK platform for a project that runs on Linux, and I would like to run it on Windows.
I've recently noticed that on the DPDK website it says that it now supports Windows also.
Is there any chance that my application would be able to run with PcapPlusPlus and DPDK on windows? does it capable of doing that?
Best regards,
Hagai.

**Comment by HagaiVinik** [comment]
Hi @seladb, is that a quick fix or a big change? 
Can you please note all the steps that need to be done for this? I'll see if i can clear some time for this.
Thank's a lot,
Hagai.

**Comment by seladb** [comment]
@HagaiVinik it depends if DPDK on Windows has feature parity with Linux, meaning all of the DPDK APIs used in PcapPlusPlus work the same way on Windows. Assuming yes, there is not a lot of work to make it work:
- Adjust the windows configuration scripts to allow using DPDK: [`configure-windows-mingw.bat`](https://github.com/seladb/PcapPlusPlus/blob/master/configure-windows-mingw.bat) (if DPDK can work with MinGW), [`configure-windows-visual-studio.bat`](https://github.com/seladb/PcapPlusPlus/blob/master/configure-windows-visual-studio.bat) (if DPDK can work with MSVC)
- Create a Windows DPDK setup script similar to [`setup_dpdk.py`](https://github.com/seladb/PcapPlusPlus/blob/master/mk/setup_dpdk.py)
- Add Windows DPDK build to the [CI](https://github.com/seladb/PcapPlusPlus/blob/master/.github/workflows/build_and_test.yml) - need to think how to do this because on Linux we run PcapPlusPlus in a docker container where DPDK is already built - this saves a lot of time because building DPDK takes several minutes. Docker support for Windows is very limited so I guess we need to find another way - maybe build DPDK once and download it from somewhere?
- Add [documentation](https://github.com/PcapPlusPlus/pcapplusplus.github.io/blob/master/docs/dpdk.md) on how to build and run PcapPlusPlus with DPDK on Windows. Here is the page on PcapPlusPlus web-site: https://pcapplusplus.github.io/docs/dpdk

My concern is that DPDK might not work in the same way on Windows, in which case we'll need code changes on top of the changes mentioned above.

**Comment by seladb** [comment]
@HagaiVinik what should we do with this issue? Can we close it?

**Comment by HagaiVinik** [comment]
Honestly Idk, I’d like to clear some time to solve this issue, but I’m really busy this days. 
I guess you can close this for now and maybe in the future we’ll discuss again about this.

**Comment by seladb** [comment]
Thanks! I'll close this issue for now, please feel free to reopen it if you start working on it
