### ISSUE TITLE
tcpReassembly fails to recover out-of-order frame

### ISSUE THREAD

**Issue by siilky** [seladb/PcapPlusPlus#851]
using 21.05 release (I guess there were no significant changes for reassembly since that), tcpReassembly.exe from samples.
Last correct data arrives at frame 87 (of length 165) (starting from 0x2E16 at the stream)
After that tcpReassembly gives [42 bytes missing] however next data should come from frame 121 (of len 42) as it does for wireshark follow TCP stream at least.
Next frames seems to be ok, though then there are missing bytes again at the end of stream (for same reason I guess)

[stream2.zip](https://github.com/seladb/PcapPlusPlus/files/8355930/stream2.zip)

**Comment by seladb** [comment]
Hi @siilky !
From looking at the sample attached I think the reason is because the next frame (88) contains data from the other side of the connection. There is an assumption [documented here](https://github.com/seladb/PcapPlusPlus/blob/master/Packet%2B%2B/src/TcpReassembly.cpp#L242-L251) that once we see data from the other side, we can treat the data from the current side as lost, because data from the other side indicates that the other side received the entire message and now responds back, however some of this data was probably lost during the packet capture. This assumption is not always true (like in your case), but I needed to make it to be able to release the out-of-order fragments waiting in the buffer.
You can treat it as kind of a limitation of the TCP reassembly engine...

**Comment by siilky** [comment]
Thank you for your answer,
I might understand the reason behind releasing extra fragments, but if my understanding is correct, there is another OO fragments management mechanism as the pending OO fragment limit. 
Do you think keeping some reasonable count for OO fragments by default (instead of unlimited) can cover all cases of keeping OO fragments from uncontrolled growth and probably correct handling of the original issue could be implemented instead of just dropping frames?

**Comment by seladb** [comment]
It's not only about releasing the extra fragments, but it's also about deciding when a message ends. Imagine a simple HTTP stream that has requests and responses: if one of the requests has missing data and we wait until we see the missing bytes we might mix requests together, for example:
```text
(1) GET  <-- has some missing bytes
(2) 200 OK
(3) GET
(4) The missing bytes from message (1)
(5) 200 OK
```

If we wait until we see (4) we'll treat requests (1) and (3) as one message instead of two.

Also, if the missing bytes don't arrive (imagine message (4) isn't there) we'll also treat requests (1) and (3) as one message but with missing data.

**Comment by seladb** [comment]
@siilky let me know if you have any questions or comments and if we can close the issue

**Comment by siilky** [comment]
I've noticed recent commit e0aa9b6de5f3f8fa7c5787b7d0e0e874ae40f37a adding option to disable ooo fragments purge, and once it is here it pretty solves my issue. 
(didn't see that PR was there for like a year, happy it is in, finally =))

**Comment by seladb** [comment]
Awesome thanks! I guess we can close the issue for now, please reopen if needed
