### ISSUE TITLE
IP-Layer contains Ethernet padding as data

### ISSUE THREAD

**Issue by jannik3141** [seladb/PcapPlusPlus#91]
Hi,
first of all, thank you so much. This library is awesome :)

I found some cases (very short packages with Ethernet padding), where the DataLen field of the IPv4Layer is longer than the "Total Length" IP-header field (eg. in Wireshark). The difference is the length of the Ethernet padding so I assume the padding is seen as IP-payload. Maybe it is possible to use the right DataLen value from the IP-header (care byte order) on IPv4Layer creation.

Best regards, Jannik

**Comment by seladb** [comment]
Hi @jannik3141 , thanks for the great feedback :)
The change you're proposing is not an easy one because in the current design it is assumed that each layer contains all of the data from where it starts to the end of the packet.
How critical is this fix for you?

**Comment by jannik3141** [comment]
Hi,
sorry for the late response. I stumbled upon this when using the DataLen field to calculate if a TCP packet has empty payload. I now use the information from the IP-header, so a fix is not critical for me. 

However I don't know if the bug influences other functionalities, because it causes the IP/TCP/UDPLayer to contain wrong data. Yet this happens only in very short packages, where Ethernet padding is actually applied. I submitted this issue to rather allow you or others with better internal knowledge of Pcap++ than me to estimate the impact of the problem.

So I am fine without a fix and will report, if found, further information or problems regarding this issue.

**Comment by seladb** [comment]
Thanks @jannik3141 ! I'm actually working on a fix. It's quite deep in code but I think I'll manage to do this change. I'll update once I'm done

**Comment by jannik3141** [comment]
Ok, great! Probably an important fix.
Funnily I've watched through TcpReassembly.cpp and found the same workaround that I used for calculating the payload size.

**Comment by seladb** [comment]
This issue is fixed. I added [pcpp::PacketTrailerLayer](http://seladb.github.io/PcapPlusPlus-Doc/Documentation/a00106.html) which represents the packet trailer/padding layer and also fixed `pcpp::IPv4Layer` and `pcpp::IPv6Layer` to set their data length according to the value in the IP header. So now, during packet parsing, if data is left after parsing is over, this data is assumed to be the packet trailer and `pcpp::Packet` creates `pcpp::PacketTrailerLayer` as the last layer in the packet.

If that's ok with you I'll close the issue now, please re-open it if you think this is not resolved

**Comment by jannik3141** [comment]
Thanks, @seladb , good idea to create PacketTrailerLayer. If (while parsing a packet) TCP/UDP data length is calculated from IP-Layer data length, then it should work fine now.
