### ISSUE TITLE
Is it possible to get IPv6 address for a PcapLiveDevice

### ISSUE THREAD

**Issue by HIGGSSAM** [seladb/PcapPlusPlus#959]
Currently you have a function, PcapLiveDevice::getIPv4Address(). Is it possible to have an equivalent to return the IPv6 addresses from a live device? Thanks

**Comment by seladb** [comment]
PcapPlusPlus currently doesn't have this functionality but it should be fairly simple to implement. The implementation would be very similar to this:
https://github.com/seladb/PcapPlusPlus/blob/master/Pcap%2B%2B/src/PcapLiveDeviceList.cpp#L264

The difference is that instead of searching for a specific IPv6 address, `PcapLiveDevice::getIPv6Address()` would simply return the first address available.

@HIGGSSAM would you consider adding this to `PcapLiveDevice`?

**Comment by jafar75** [comment]
@seladb If it helps, I will try to add this feature.

**Comment by seladb** [comment]
Sure @jafar75 , that'd be great, thank you!

**Comment by jafar75** [comment]
#965

**Comment by HIGGSSAM** [comment]
Applogies I have been abit busy this week writing my disseration. @jafar75 I started doing this but haven't quite finsihed it yet, so if you have done it then great!

**Comment by seladb** [comment]
Added in #965 

Thank you @jafar75 for working on this, much appreciated! 🙏 ❤️
